/* Generated by tools/check-demo-engines.py. The page reports
   these numbers; they are the result of comparing
   demo/lexer.js and demo/parser.js against bin/matrixc over
   every program in examples/. */
window.MATRIXLANG_AGREEMENT = {
 "programs": 21,
 "accepted": 18,
 "rejected": 3,
 "tokens": 1179,
 "diagnostics": 10,
 "disagreements": 0,
 "compiler": "matrixc.exe"
};
