/* Generated by tools/build-grammar.py from src/frontend/matrix.y and src/frontend/matrix.l.
   Do not edit by hand: these are bison's own tables, read
   out of `bison --report=all`, and the page parses with
   them. Editing this file would make the demo parse a
   grammar the compiler does not have. */
window.MATRIXLANG_GRAMMAR = {
 "bison": "bison (GNU Bison) 3.8.2",
 "grammarFile": "src/frontend/matrix.y",
 "scannerFile": "src/frontend/matrix.l",
 "start": "program",
 "rules": [
  {
   "n": 0,
   "lhs": "$accept",
   "rhs": [
    "program",
    "$end"
   ],
   "empty": false
  },
  {
   "n": 1,
   "lhs": "program",
   "rhs": [
    "stmt_list"
   ],
   "empty": false
  },
  {
   "n": 2,
   "lhs": "stmt_list",
   "rhs": [],
   "empty": true
  },
  {
   "n": 3,
   "lhs": "stmt_list",
   "rhs": [
    "stmt_list",
    "stmt"
   ],
   "empty": false
  },
  {
   "n": 4,
   "lhs": "stmt",
   "rhs": [
    "decl"
   ],
   "empty": false
  },
  {
   "n": 5,
   "lhs": "stmt",
   "rhs": [
    "assign"
   ],
   "empty": false
  },
  {
   "n": 6,
   "lhs": "stmt",
   "rhs": [
    "print_stmt"
   ],
   "empty": false
  },
  {
   "n": 7,
   "lhs": "stmt",
   "rhs": [
    "';'"
   ],
   "empty": false
  },
  {
   "n": 8,
   "lhs": "stmt",
   "rhs": [
    "error",
    "';'"
   ],
   "empty": false
  },
  {
   "n": 9,
   "lhs": "decl",
   "rhs": [
    "KW_MATRIX",
    "IDENT",
    "'['",
    "NUMBER",
    "','",
    "NUMBER",
    "']'",
    "';'"
   ],
   "empty": false
  },
  {
   "n": 10,
   "lhs": "decl",
   "rhs": [
    "KW_MATRIX",
    "IDENT",
    "'['",
    "NUMBER",
    "','",
    "NUMBER",
    "']'",
    "'='",
    "expr",
    "';'"
   ],
   "empty": false
  },
  {
   "n": 11,
   "lhs": "decl",
   "rhs": [
    "KW_MATRIX",
    "IDENT",
    "'='",
    "expr",
    "';'"
   ],
   "empty": false
  },
  {
   "n": 12,
   "lhs": "decl",
   "rhs": [
    "KW_SCALAR",
    "IDENT",
    "';'"
   ],
   "empty": false
  },
  {
   "n": 13,
   "lhs": "decl",
   "rhs": [
    "KW_SCALAR",
    "IDENT",
    "'='",
    "expr",
    "';'"
   ],
   "empty": false
  },
  {
   "n": 14,
   "lhs": "assign",
   "rhs": [
    "IDENT",
    "'='",
    "expr",
    "';'"
   ],
   "empty": false
  },
  {
   "n": 15,
   "lhs": "print_stmt",
   "rhs": [
    "KW_PRINT",
    "'('",
    "expr",
    "')'",
    "';'"
   ],
   "empty": false
  },
  {
   "n": 16,
   "lhs": "expr",
   "rhs": [
    "expr",
    "'+'",
    "expr"
   ],
   "empty": false
  },
  {
   "n": 17,
   "lhs": "expr",
   "rhs": [
    "expr",
    "'-'",
    "expr"
   ],
   "empty": false
  },
  {
   "n": 18,
   "lhs": "expr",
   "rhs": [
    "expr",
    "'*'",
    "expr"
   ],
   "empty": false
  },
  {
   "n": 19,
   "lhs": "expr",
   "rhs": [
    "'-'",
    "expr"
   ],
   "empty": false
  },
  {
   "n": 20,
   "lhs": "expr",
   "rhs": [
    "KW_TRANSPOSE",
    "'('",
    "expr",
    "')'"
   ],
   "empty": false
  },
  {
   "n": 21,
   "lhs": "expr",
   "rhs": [
    "KW_IDENTITY",
    "'('",
    "expr",
    "')'"
   ],
   "empty": false
  },
  {
   "n": 22,
   "lhs": "expr",
   "rhs": [
    "KW_ZEROS",
    "'('",
    "expr",
    "','",
    "expr",
    "')'"
   ],
   "empty": false
  },
  {
   "n": 23,
   "lhs": "expr",
   "rhs": [
    "KW_ONES",
    "'('",
    "expr",
    "','",
    "expr",
    "')'"
   ],
   "empty": false
  },
  {
   "n": 24,
   "lhs": "expr",
   "rhs": [
    "'('",
    "expr",
    "')'"
   ],
   "empty": false
  },
  {
   "n": 25,
   "lhs": "expr",
   "rhs": [
    "matrix_literal"
   ],
   "empty": false
  },
  {
   "n": 26,
   "lhs": "expr",
   "rhs": [
    "NUMBER"
   ],
   "empty": false
  },
  {
   "n": 27,
   "lhs": "expr",
   "rhs": [
    "IDENT"
   ],
   "empty": false
  },
  {
   "n": 28,
   "lhs": "matrix_literal",
   "rhs": [
    "'{'",
    "row_list",
    "'}'"
   ],
   "empty": false
  },
  {
   "n": 29,
   "lhs": "row_list",
   "rhs": [
    "row"
   ],
   "empty": false
  },
  {
   "n": 30,
   "lhs": "row_list",
   "rhs": [
    "row_list",
    "','",
    "row"
   ],
   "empty": false
  },
  {
   "n": 31,
   "lhs": "row",
   "rhs": [
    "'{'",
    "num_list",
    "'}'"
   ],
   "empty": false
  },
  {
   "n": 32,
   "lhs": "num_list",
   "rhs": [
    "expr"
   ],
   "empty": false
  },
  {
   "n": 33,
   "lhs": "num_list",
   "rhs": [
    "num_list",
    "','",
    "expr"
   ],
   "empty": false
  }
 ],
 "terminals": [
  {
   "name": "$end",
   "code": 0,
   "rules": [
    0
   ]
  },
  {
   "name": "'('",
   "code": 40,
   "rules": [
    15,
    20,
    21,
    22,
    23,
    24
   ]
  },
  {
   "name": "')'",
   "code": 41,
   "rules": [
    15,
    20,
    21,
    22,
    23,
    24
   ]
  },
  {
   "name": "'*'",
   "code": 42,
   "rules": [
    18
   ]
  },
  {
   "name": "'+'",
   "code": 43,
   "rules": [
    16
   ]
  },
  {
   "name": "','",
   "code": 44,
   "rules": [
    9,
    10,
    22,
    23,
    30,
    33
   ]
  },
  {
   "name": "'-'",
   "code": 45,
   "rules": [
    17,
    19
   ]
  },
  {
   "name": "';'",
   "code": 59,
   "rules": [
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15
   ]
  },
  {
   "name": "'='",
   "code": 61,
   "rules": [
    10,
    11,
    13,
    14
   ]
  },
  {
   "name": "'['",
   "code": 91,
   "rules": [
    9,
    10
   ]
  },
  {
   "name": "']'",
   "code": 93,
   "rules": [
    9,
    10
   ]
  },
  {
   "name": "'{'",
   "code": 123,
   "rules": [
    28,
    31
   ]
  },
  {
   "name": "'}'",
   "code": 125,
   "rules": [
    28,
    31
   ]
  },
  {
   "name": "error",
   "code": 256,
   "rules": [
    8
   ]
  },
  {
   "name": "IDENT",
   "code": 258,
   "rules": [
    9,
    10,
    11,
    12,
    13,
    14,
    27
   ]
  },
  {
   "name": "NUMBER",
   "code": 259,
   "rules": [
    9,
    10,
    26
   ]
  },
  {
   "name": "KW_MATRIX",
   "code": 260,
   "rules": [
    9,
    10,
    11
   ]
  },
  {
   "name": "KW_SCALAR",
   "code": 261,
   "rules": [
    12,
    13
   ]
  },
  {
   "name": "KW_PRINT",
   "code": 262,
   "rules": [
    15
   ]
  },
  {
   "name": "KW_TRANSPOSE",
   "code": 263,
   "rules": [
    20
   ]
  },
  {
   "name": "KW_IDENTITY",
   "code": 264,
   "rules": [
    21
   ]
  },
  {
   "name": "KW_ZEROS",
   "code": 265,
   "rules": [
    22
   ]
  },
  {
   "name": "KW_ONES",
   "code": 266,
   "rules": [
    23
   ]
  },
  {
   "name": "UMINUS",
   "code": 267,
   "rules": []
  }
 ],
 "nonterminals": [
  {
   "name": "$accept",
   "left": [
    0
   ],
   "right": []
  },
  {
   "name": "program",
   "left": [
    1
   ],
   "right": [
    0
   ]
  },
  {
   "name": "stmt_list",
   "left": [
    2,
    3
   ],
   "right": [
    1,
    3
   ]
  },
  {
   "name": "stmt",
   "left": [
    4,
    5,
    6,
    7,
    8
   ],
   "right": [
    3
   ]
  },
  {
   "name": "decl",
   "left": [
    9,
    10,
    11,
    12,
    13
   ],
   "right": [
    4
   ]
  },
  {
   "name": "assign",
   "left": [
    14
   ],
   "right": [
    5
   ]
  },
  {
   "name": "print_stmt",
   "left": [
    15
   ],
   "right": [
    6
   ]
  },
  {
   "name": "expr",
   "left": [
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27
   ],
   "right": [
    10,
    11,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    32,
    33
   ]
  },
  {
   "name": "matrix_literal",
   "left": [
    28
   ],
   "right": [
    25
   ]
  },
  {
   "name": "row_list",
   "left": [
    29,
    30
   ],
   "right": [
    28,
    30
   ]
  },
  {
   "name": "row",
   "left": [
    31
   ],
   "right": [
    29,
    30
   ]
  },
  {
   "name": "num_list",
   "left": [
    32,
    33
   ],
   "right": [
    31,
    33
   ]
  }
 ],
 "states": [
  {
   "id": 0,
   "items": [
    {
     "rule": 0,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 1,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 2,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 3,
     "dot": 0,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 2
   },
   "gotos": {
    "program": 1,
    "stmt_list": 2
   },
   "resolved": []
  },
  {
   "id": 1,
   "items": [
    {
     "rule": 0,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {
    "$end": {
     "kind": "shift",
     "to": 3
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 2,
   "items": [
    {
     "rule": 1,
     "dot": 1,
     "lookahead": [
      "$end"
     ]
    },
    {
     "rule": 3,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 4,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 5,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 6,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 7,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 8,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 9,
     "dot": 0,
     "lookahead": [
      "' NUMBER '",
      "' NUMBER '",
      "' '"
     ]
    },
    {
     "rule": 10,
     "dot": 0,
     "lookahead": [
      "' NUMBER '",
      "' NUMBER '",
      "' '",
      "' expr '"
     ]
    },
    {
     "rule": 11,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 12,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 13,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 14,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 15,
     "dot": 0,
     "lookahead": []
    }
   ],
   "actions": {
    "error": {
     "kind": "shift",
     "to": 4
    },
    "IDENT": {
     "kind": "shift",
     "to": 5
    },
    "KW_MATRIX": {
     "kind": "shift",
     "to": 6
    },
    "KW_SCALAR": {
     "kind": "shift",
     "to": 7
    },
    "KW_PRINT": {
     "kind": "shift",
     "to": 8
    },
    "';'": {
     "kind": "shift",
     "to": 9
    },
    "$end": {
     "kind": "reduce",
     "rule": 1
    }
   },
   "default": null,
   "gotos": {
    "stmt": 10,
    "decl": 11,
    "assign": 12,
    "print_stmt": 13
   },
   "resolved": []
  },
  {
   "id": 3,
   "items": [
    {
     "rule": 0,
     "dot": 2,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "accept"
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 4,
   "items": [
    {
     "rule": 8,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {
    "';'": {
     "kind": "shift",
     "to": 14
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 5,
   "items": [
    {
     "rule": 14,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {
    "'='": {
     "kind": "shift",
     "to": 15
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 6,
   "items": [
    {
     "rule": 9,
     "dot": 1,
     "lookahead": [
      "' NUMBER '",
      "' NUMBER '",
      "' '"
     ]
    },
    {
     "rule": 10,
     "dot": 1,
     "lookahead": [
      "' NUMBER '",
      "' NUMBER '",
      "' '",
      "' expr '"
     ]
    },
    {
     "rule": 11,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {
    "IDENT": {
     "kind": "shift",
     "to": 16
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 7,
   "items": [
    {
     "rule": 12,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 13,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {
    "IDENT": {
     "kind": "shift",
     "to": 17
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 8,
   "items": [
    {
     "rule": 15,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {
    "'('": {
     "kind": "shift",
     "to": 18
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 9,
   "items": [
    {
     "rule": 7,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 7
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 10,
   "items": [
    {
     "rule": 3,
     "dot": 2,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 3
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 11,
   "items": [
    {
     "rule": 4,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 4
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 12,
   "items": [
    {
     "rule": 5,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 5
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 13,
   "items": [
    {
     "rule": 6,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 6
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 14,
   "items": [
    {
     "rule": 8,
     "dot": 2,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 8
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 15,
   "items": [
    {
     "rule": 14,
     "dot": 2,
     "lookahead": []
    },
    {
     "rule": 16,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 19,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 20,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 21,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 22,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 23,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 24,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 25,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 26,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 27,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 28,
     "dot": 0,
     "lookahead": []
    }
   ],
   "actions": {
    "IDENT": {
     "kind": "shift",
     "to": 19
    },
    "NUMBER": {
     "kind": "shift",
     "to": 20
    },
    "KW_TRANSPOSE": {
     "kind": "shift",
     "to": 21
    },
    "KW_IDENTITY": {
     "kind": "shift",
     "to": 22
    },
    "KW_ZEROS": {
     "kind": "shift",
     "to": 23
    },
    "KW_ONES": {
     "kind": "shift",
     "to": 24
    },
    "'-'": {
     "kind": "shift",
     "to": 25
    },
    "'('": {
     "kind": "shift",
     "to": 26
    },
    "'{'": {
     "kind": "shift",
     "to": 27
    }
   },
   "default": null,
   "gotos": {
    "expr": 28,
    "matrix_literal": 29
   },
   "resolved": []
  },
  {
   "id": 16,
   "items": [
    {
     "rule": 9,
     "dot": 2,
     "lookahead": [
      "' NUMBER '",
      "' NUMBER '",
      "' '"
     ]
    },
    {
     "rule": 10,
     "dot": 2,
     "lookahead": [
      "' NUMBER '",
      "' NUMBER '",
      "' '",
      "' expr '"
     ]
    },
    {
     "rule": 11,
     "dot": 2,
     "lookahead": []
    }
   ],
   "actions": {
    "'['": {
     "kind": "shift",
     "to": 30
    },
    "'='": {
     "kind": "shift",
     "to": 31
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 17,
   "items": [
    {
     "rule": 12,
     "dot": 2,
     "lookahead": []
    },
    {
     "rule": 13,
     "dot": 2,
     "lookahead": []
    }
   ],
   "actions": {
    "';'": {
     "kind": "shift",
     "to": 32
    },
    "'='": {
     "kind": "shift",
     "to": 33
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 18,
   "items": [
    {
     "rule": 15,
     "dot": 2,
     "lookahead": []
    },
    {
     "rule": 16,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 19,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 20,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 21,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 22,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 23,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 24,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 25,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 26,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 27,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 28,
     "dot": 0,
     "lookahead": []
    }
   ],
   "actions": {
    "IDENT": {
     "kind": "shift",
     "to": 19
    },
    "NUMBER": {
     "kind": "shift",
     "to": 20
    },
    "KW_TRANSPOSE": {
     "kind": "shift",
     "to": 21
    },
    "KW_IDENTITY": {
     "kind": "shift",
     "to": 22
    },
    "KW_ZEROS": {
     "kind": "shift",
     "to": 23
    },
    "KW_ONES": {
     "kind": "shift",
     "to": 24
    },
    "'-'": {
     "kind": "shift",
     "to": 25
    },
    "'('": {
     "kind": "shift",
     "to": 26
    },
    "'{'": {
     "kind": "shift",
     "to": 27
    }
   },
   "default": null,
   "gotos": {
    "expr": 34,
    "matrix_literal": 29
   },
   "resolved": []
  },
  {
   "id": 19,
   "items": [
    {
     "rule": 27,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 27
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 20,
   "items": [
    {
     "rule": 26,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 26
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 21,
   "items": [
    {
     "rule": 20,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {
    "'('": {
     "kind": "shift",
     "to": 35
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 22,
   "items": [
    {
     "rule": 21,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {
    "'('": {
     "kind": "shift",
     "to": 36
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 23,
   "items": [
    {
     "rule": 22,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {
    "'('": {
     "kind": "shift",
     "to": 37
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 24,
   "items": [
    {
     "rule": 23,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {
    "'('": {
     "kind": "shift",
     "to": 38
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 25,
   "items": [
    {
     "rule": 16,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 19,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 19,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 20,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 21,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 22,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 23,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 24,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 25,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 26,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 27,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 28,
     "dot": 0,
     "lookahead": []
    }
   ],
   "actions": {
    "IDENT": {
     "kind": "shift",
     "to": 19
    },
    "NUMBER": {
     "kind": "shift",
     "to": 20
    },
    "KW_TRANSPOSE": {
     "kind": "shift",
     "to": 21
    },
    "KW_IDENTITY": {
     "kind": "shift",
     "to": 22
    },
    "KW_ZEROS": {
     "kind": "shift",
     "to": 23
    },
    "KW_ONES": {
     "kind": "shift",
     "to": 24
    },
    "'-'": {
     "kind": "shift",
     "to": 25
    },
    "'('": {
     "kind": "shift",
     "to": 26
    },
    "'{'": {
     "kind": "shift",
     "to": 27
    }
   },
   "default": null,
   "gotos": {
    "expr": 39,
    "matrix_literal": 29
   },
   "resolved": []
  },
  {
   "id": 26,
   "items": [
    {
     "rule": 16,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 19,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 20,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 21,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 22,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 23,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 24,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 24,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 25,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 26,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 27,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 28,
     "dot": 0,
     "lookahead": []
    }
   ],
   "actions": {
    "IDENT": {
     "kind": "shift",
     "to": 19
    },
    "NUMBER": {
     "kind": "shift",
     "to": 20
    },
    "KW_TRANSPOSE": {
     "kind": "shift",
     "to": 21
    },
    "KW_IDENTITY": {
     "kind": "shift",
     "to": 22
    },
    "KW_ZEROS": {
     "kind": "shift",
     "to": 23
    },
    "KW_ONES": {
     "kind": "shift",
     "to": 24
    },
    "'-'": {
     "kind": "shift",
     "to": 25
    },
    "'('": {
     "kind": "shift",
     "to": 26
    },
    "'{'": {
     "kind": "shift",
     "to": 27
    }
   },
   "default": null,
   "gotos": {
    "expr": 40,
    "matrix_literal": 29
   },
   "resolved": []
  },
  {
   "id": 27,
   "items": [
    {
     "rule": 28,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 29,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 30,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 31,
     "dot": 0,
     "lookahead": []
    }
   ],
   "actions": {
    "'{'": {
     "kind": "shift",
     "to": 41
    }
   },
   "default": null,
   "gotos": {
    "row_list": 42,
    "row": 43
   },
   "resolved": []
  },
  {
   "id": 28,
   "items": [
    {
     "rule": 14,
     "dot": 3,
     "lookahead": []
    },
    {
     "rule": 16,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {
    "'+'": {
     "kind": "shift",
     "to": 44
    },
    "'-'": {
     "kind": "shift",
     "to": 45
    },
    "'*'": {
     "kind": "shift",
     "to": 46
    },
    "';'": {
     "kind": "shift",
     "to": 47
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 29,
   "items": [
    {
     "rule": 25,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 25
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 30,
   "items": [
    {
     "rule": 9,
     "dot": 3,
     "lookahead": [
      "' . NUMBER '",
      "' NUMBER '",
      "' '"
     ]
    },
    {
     "rule": 10,
     "dot": 3,
     "lookahead": [
      "' . NUMBER '",
      "' NUMBER '",
      "' '",
      "' expr '"
     ]
    }
   ],
   "actions": {
    "NUMBER": {
     "kind": "shift",
     "to": 48
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 31,
   "items": [
    {
     "rule": 11,
     "dot": 3,
     "lookahead": []
    },
    {
     "rule": 16,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 19,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 20,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 21,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 22,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 23,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 24,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 25,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 26,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 27,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 28,
     "dot": 0,
     "lookahead": []
    }
   ],
   "actions": {
    "IDENT": {
     "kind": "shift",
     "to": 19
    },
    "NUMBER": {
     "kind": "shift",
     "to": 20
    },
    "KW_TRANSPOSE": {
     "kind": "shift",
     "to": 21
    },
    "KW_IDENTITY": {
     "kind": "shift",
     "to": 22
    },
    "KW_ZEROS": {
     "kind": "shift",
     "to": 23
    },
    "KW_ONES": {
     "kind": "shift",
     "to": 24
    },
    "'-'": {
     "kind": "shift",
     "to": 25
    },
    "'('": {
     "kind": "shift",
     "to": 26
    },
    "'{'": {
     "kind": "shift",
     "to": 27
    }
   },
   "default": null,
   "gotos": {
    "expr": 49,
    "matrix_literal": 29
   },
   "resolved": []
  },
  {
   "id": 32,
   "items": [
    {
     "rule": 12,
     "dot": 3,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 12
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 33,
   "items": [
    {
     "rule": 13,
     "dot": 3,
     "lookahead": []
    },
    {
     "rule": 16,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 19,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 20,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 21,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 22,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 23,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 24,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 25,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 26,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 27,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 28,
     "dot": 0,
     "lookahead": []
    }
   ],
   "actions": {
    "IDENT": {
     "kind": "shift",
     "to": 19
    },
    "NUMBER": {
     "kind": "shift",
     "to": 20
    },
    "KW_TRANSPOSE": {
     "kind": "shift",
     "to": 21
    },
    "KW_IDENTITY": {
     "kind": "shift",
     "to": 22
    },
    "KW_ZEROS": {
     "kind": "shift",
     "to": 23
    },
    "KW_ONES": {
     "kind": "shift",
     "to": 24
    },
    "'-'": {
     "kind": "shift",
     "to": 25
    },
    "'('": {
     "kind": "shift",
     "to": 26
    },
    "'{'": {
     "kind": "shift",
     "to": 27
    }
   },
   "default": null,
   "gotos": {
    "expr": 50,
    "matrix_literal": 29
   },
   "resolved": []
  },
  {
   "id": 34,
   "items": [
    {
     "rule": 15,
     "dot": 3,
     "lookahead": []
    },
    {
     "rule": 16,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {
    "'+'": {
     "kind": "shift",
     "to": 44
    },
    "'-'": {
     "kind": "shift",
     "to": 45
    },
    "'*'": {
     "kind": "shift",
     "to": 46
    },
    "')'": {
     "kind": "shift",
     "to": 51
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 35,
   "items": [
    {
     "rule": 16,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 19,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 20,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 20,
     "dot": 2,
     "lookahead": []
    },
    {
     "rule": 21,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 22,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 23,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 24,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 25,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 26,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 27,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 28,
     "dot": 0,
     "lookahead": []
    }
   ],
   "actions": {
    "IDENT": {
     "kind": "shift",
     "to": 19
    },
    "NUMBER": {
     "kind": "shift",
     "to": 20
    },
    "KW_TRANSPOSE": {
     "kind": "shift",
     "to": 21
    },
    "KW_IDENTITY": {
     "kind": "shift",
     "to": 22
    },
    "KW_ZEROS": {
     "kind": "shift",
     "to": 23
    },
    "KW_ONES": {
     "kind": "shift",
     "to": 24
    },
    "'-'": {
     "kind": "shift",
     "to": 25
    },
    "'('": {
     "kind": "shift",
     "to": 26
    },
    "'{'": {
     "kind": "shift",
     "to": 27
    }
   },
   "default": null,
   "gotos": {
    "expr": 52,
    "matrix_literal": 29
   },
   "resolved": []
  },
  {
   "id": 36,
   "items": [
    {
     "rule": 16,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 19,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 20,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 21,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 21,
     "dot": 2,
     "lookahead": []
    },
    {
     "rule": 22,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 23,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 24,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 25,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 26,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 27,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 28,
     "dot": 0,
     "lookahead": []
    }
   ],
   "actions": {
    "IDENT": {
     "kind": "shift",
     "to": 19
    },
    "NUMBER": {
     "kind": "shift",
     "to": 20
    },
    "KW_TRANSPOSE": {
     "kind": "shift",
     "to": 21
    },
    "KW_IDENTITY": {
     "kind": "shift",
     "to": 22
    },
    "KW_ZEROS": {
     "kind": "shift",
     "to": 23
    },
    "KW_ONES": {
     "kind": "shift",
     "to": 24
    },
    "'-'": {
     "kind": "shift",
     "to": 25
    },
    "'('": {
     "kind": "shift",
     "to": 26
    },
    "'{'": {
     "kind": "shift",
     "to": 27
    }
   },
   "default": null,
   "gotos": {
    "expr": 53,
    "matrix_literal": 29
   },
   "resolved": []
  },
  {
   "id": 37,
   "items": [
    {
     "rule": 16,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 19,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 20,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 21,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 22,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 22,
     "dot": 2,
     "lookahead": []
    },
    {
     "rule": 23,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 24,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 25,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 26,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 27,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 28,
     "dot": 0,
     "lookahead": []
    }
   ],
   "actions": {
    "IDENT": {
     "kind": "shift",
     "to": 19
    },
    "NUMBER": {
     "kind": "shift",
     "to": 20
    },
    "KW_TRANSPOSE": {
     "kind": "shift",
     "to": 21
    },
    "KW_IDENTITY": {
     "kind": "shift",
     "to": 22
    },
    "KW_ZEROS": {
     "kind": "shift",
     "to": 23
    },
    "KW_ONES": {
     "kind": "shift",
     "to": 24
    },
    "'-'": {
     "kind": "shift",
     "to": 25
    },
    "'('": {
     "kind": "shift",
     "to": 26
    },
    "'{'": {
     "kind": "shift",
     "to": 27
    }
   },
   "default": null,
   "gotos": {
    "expr": 54,
    "matrix_literal": 29
   },
   "resolved": []
  },
  {
   "id": 38,
   "items": [
    {
     "rule": 16,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 19,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 20,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 21,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 22,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 23,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 23,
     "dot": 2,
     "lookahead": []
    },
    {
     "rule": 24,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 25,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 26,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 27,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 28,
     "dot": 0,
     "lookahead": []
    }
   ],
   "actions": {
    "IDENT": {
     "kind": "shift",
     "to": 19
    },
    "NUMBER": {
     "kind": "shift",
     "to": 20
    },
    "KW_TRANSPOSE": {
     "kind": "shift",
     "to": 21
    },
    "KW_IDENTITY": {
     "kind": "shift",
     "to": 22
    },
    "KW_ZEROS": {
     "kind": "shift",
     "to": 23
    },
    "KW_ONES": {
     "kind": "shift",
     "to": 24
    },
    "'-'": {
     "kind": "shift",
     "to": 25
    },
    "'('": {
     "kind": "shift",
     "to": 26
    },
    "'{'": {
     "kind": "shift",
     "to": 27
    }
   },
   "default": null,
   "gotos": {
    "expr": 55,
    "matrix_literal": 29
   },
   "resolved": []
  },
  {
   "id": 39,
   "items": [
    {
     "rule": 16,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 19,
     "dot": 2,
     "lookahead": [
      "'+'",
      "'-'",
      "'*'",
      "';'",
      "','",
      "')'",
      "'}'"
     ]
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 19
   },
   "gotos": {},
   "resolved": [
    {
     "rule": 19,
     "token": "'+'",
     "as": "reduce",
     "why": "'+' < UMINUS"
    },
    {
     "rule": 19,
     "token": "'-'",
     "as": "reduce",
     "why": "'-' < UMINUS"
    },
    {
     "rule": 19,
     "token": "'*'",
     "as": "reduce",
     "why": "'*' < UMINUS"
    }
   ]
  },
  {
   "id": 40,
   "items": [
    {
     "rule": 16,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 24,
     "dot": 2,
     "lookahead": []
    }
   ],
   "actions": {
    "'+'": {
     "kind": "shift",
     "to": 44
    },
    "'-'": {
     "kind": "shift",
     "to": 45
    },
    "'*'": {
     "kind": "shift",
     "to": 46
    },
    "')'": {
     "kind": "shift",
     "to": 56
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 41,
   "items": [
    {
     "rule": 16,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 19,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 20,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 21,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 22,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 23,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 24,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 25,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 26,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 27,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 28,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 31,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 32,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 33,
     "dot": 0,
     "lookahead": []
    }
   ],
   "actions": {
    "IDENT": {
     "kind": "shift",
     "to": 19
    },
    "NUMBER": {
     "kind": "shift",
     "to": 20
    },
    "KW_TRANSPOSE": {
     "kind": "shift",
     "to": 21
    },
    "KW_IDENTITY": {
     "kind": "shift",
     "to": 22
    },
    "KW_ZEROS": {
     "kind": "shift",
     "to": 23
    },
    "KW_ONES": {
     "kind": "shift",
     "to": 24
    },
    "'-'": {
     "kind": "shift",
     "to": 25
    },
    "'('": {
     "kind": "shift",
     "to": 26
    },
    "'{'": {
     "kind": "shift",
     "to": 27
    }
   },
   "default": null,
   "gotos": {
    "expr": 57,
    "matrix_literal": 29,
    "num_list": 58
   },
   "resolved": []
  },
  {
   "id": 42,
   "items": [
    {
     "rule": 28,
     "dot": 2,
     "lookahead": []
    },
    {
     "rule": 30,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {
    "','": {
     "kind": "shift",
     "to": 59
    },
    "'}'": {
     "kind": "shift",
     "to": 60
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 43,
   "items": [
    {
     "rule": 29,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 29
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 44,
   "items": [
    {
     "rule": 16,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 16,
     "dot": 2,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 19,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 20,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 21,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 22,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 23,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 24,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 25,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 26,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 27,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 28,
     "dot": 0,
     "lookahead": []
    }
   ],
   "actions": {
    "IDENT": {
     "kind": "shift",
     "to": 19
    },
    "NUMBER": {
     "kind": "shift",
     "to": 20
    },
    "KW_TRANSPOSE": {
     "kind": "shift",
     "to": 21
    },
    "KW_IDENTITY": {
     "kind": "shift",
     "to": 22
    },
    "KW_ZEROS": {
     "kind": "shift",
     "to": 23
    },
    "KW_ONES": {
     "kind": "shift",
     "to": 24
    },
    "'-'": {
     "kind": "shift",
     "to": 25
    },
    "'('": {
     "kind": "shift",
     "to": 26
    },
    "'{'": {
     "kind": "shift",
     "to": 27
    }
   },
   "default": null,
   "gotos": {
    "expr": 61,
    "matrix_literal": 29
   },
   "resolved": []
  },
  {
   "id": 45,
   "items": [
    {
     "rule": 16,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 2,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 19,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 20,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 21,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 22,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 23,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 24,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 25,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 26,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 27,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 28,
     "dot": 0,
     "lookahead": []
    }
   ],
   "actions": {
    "IDENT": {
     "kind": "shift",
     "to": 19
    },
    "NUMBER": {
     "kind": "shift",
     "to": 20
    },
    "KW_TRANSPOSE": {
     "kind": "shift",
     "to": 21
    },
    "KW_IDENTITY": {
     "kind": "shift",
     "to": 22
    },
    "KW_ZEROS": {
     "kind": "shift",
     "to": 23
    },
    "KW_ONES": {
     "kind": "shift",
     "to": 24
    },
    "'-'": {
     "kind": "shift",
     "to": 25
    },
    "'('": {
     "kind": "shift",
     "to": 26
    },
    "'{'": {
     "kind": "shift",
     "to": 27
    }
   },
   "default": null,
   "gotos": {
    "expr": 62,
    "matrix_literal": 29
   },
   "resolved": []
  },
  {
   "id": 46,
   "items": [
    {
     "rule": 16,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 2,
     "lookahead": []
    },
    {
     "rule": 19,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 20,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 21,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 22,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 23,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 24,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 25,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 26,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 27,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 28,
     "dot": 0,
     "lookahead": []
    }
   ],
   "actions": {
    "IDENT": {
     "kind": "shift",
     "to": 19
    },
    "NUMBER": {
     "kind": "shift",
     "to": 20
    },
    "KW_TRANSPOSE": {
     "kind": "shift",
     "to": 21
    },
    "KW_IDENTITY": {
     "kind": "shift",
     "to": 22
    },
    "KW_ZEROS": {
     "kind": "shift",
     "to": 23
    },
    "KW_ONES": {
     "kind": "shift",
     "to": 24
    },
    "'-'": {
     "kind": "shift",
     "to": 25
    },
    "'('": {
     "kind": "shift",
     "to": 26
    },
    "'{'": {
     "kind": "shift",
     "to": 27
    }
   },
   "default": null,
   "gotos": {
    "expr": 63,
    "matrix_literal": 29
   },
   "resolved": []
  },
  {
   "id": 47,
   "items": [
    {
     "rule": 14,
     "dot": 4,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 14
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 48,
   "items": [
    {
     "rule": 9,
     "dot": 3,
     "lookahead": [
      "' NUMBER . '",
      "' NUMBER '",
      "' '"
     ]
    },
    {
     "rule": 10,
     "dot": 3,
     "lookahead": [
      "' NUMBER . '",
      "' NUMBER '",
      "' '",
      "' expr '"
     ]
    }
   ],
   "actions": {
    "','": {
     "kind": "shift",
     "to": 64
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 49,
   "items": [
    {
     "rule": 11,
     "dot": 4,
     "lookahead": []
    },
    {
     "rule": 16,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {
    "'+'": {
     "kind": "shift",
     "to": 44
    },
    "'-'": {
     "kind": "shift",
     "to": 45
    },
    "'*'": {
     "kind": "shift",
     "to": 46
    },
    "';'": {
     "kind": "shift",
     "to": 65
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 50,
   "items": [
    {
     "rule": 13,
     "dot": 4,
     "lookahead": []
    },
    {
     "rule": 16,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {
    "'+'": {
     "kind": "shift",
     "to": 44
    },
    "'-'": {
     "kind": "shift",
     "to": 45
    },
    "'*'": {
     "kind": "shift",
     "to": 46
    },
    "';'": {
     "kind": "shift",
     "to": 66
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 51,
   "items": [
    {
     "rule": 15,
     "dot": 4,
     "lookahead": []
    }
   ],
   "actions": {
    "';'": {
     "kind": "shift",
     "to": 67
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 52,
   "items": [
    {
     "rule": 16,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 20,
     "dot": 3,
     "lookahead": []
    }
   ],
   "actions": {
    "'+'": {
     "kind": "shift",
     "to": 44
    },
    "'-'": {
     "kind": "shift",
     "to": 45
    },
    "'*'": {
     "kind": "shift",
     "to": 46
    },
    "')'": {
     "kind": "shift",
     "to": 68
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 53,
   "items": [
    {
     "rule": 16,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 21,
     "dot": 3,
     "lookahead": []
    }
   ],
   "actions": {
    "'+'": {
     "kind": "shift",
     "to": 44
    },
    "'-'": {
     "kind": "shift",
     "to": 45
    },
    "'*'": {
     "kind": "shift",
     "to": 46
    },
    "')'": {
     "kind": "shift",
     "to": 69
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 54,
   "items": [
    {
     "rule": 16,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 22,
     "dot": 3,
     "lookahead": []
    }
   ],
   "actions": {
    "'+'": {
     "kind": "shift",
     "to": 44
    },
    "'-'": {
     "kind": "shift",
     "to": 45
    },
    "'*'": {
     "kind": "shift",
     "to": 46
    },
    "','": {
     "kind": "shift",
     "to": 70
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 55,
   "items": [
    {
     "rule": 16,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 23,
     "dot": 3,
     "lookahead": []
    }
   ],
   "actions": {
    "'+'": {
     "kind": "shift",
     "to": 44
    },
    "'-'": {
     "kind": "shift",
     "to": 45
    },
    "'*'": {
     "kind": "shift",
     "to": 46
    },
    "','": {
     "kind": "shift",
     "to": 71
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 56,
   "items": [
    {
     "rule": 24,
     "dot": 3,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 24
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 57,
   "items": [
    {
     "rule": 16,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 32,
     "dot": 1,
     "lookahead": [
      "','",
      "'}'"
     ]
    }
   ],
   "actions": {
    "'+'": {
     "kind": "shift",
     "to": 44
    },
    "'-'": {
     "kind": "shift",
     "to": 45
    },
    "'*'": {
     "kind": "shift",
     "to": 46
    }
   },
   "default": {
    "kind": "reduce",
    "rule": 32
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 58,
   "items": [
    {
     "rule": 31,
     "dot": 2,
     "lookahead": []
    },
    {
     "rule": 33,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {
    "','": {
     "kind": "shift",
     "to": 72
    },
    "'}'": {
     "kind": "shift",
     "to": 73
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 59,
   "items": [
    {
     "rule": 30,
     "dot": 2,
     "lookahead": []
    },
    {
     "rule": 31,
     "dot": 0,
     "lookahead": []
    }
   ],
   "actions": {
    "'{'": {
     "kind": "shift",
     "to": 41
    }
   },
   "default": null,
   "gotos": {
    "row": 74
   },
   "resolved": []
  },
  {
   "id": 60,
   "items": [
    {
     "rule": 28,
     "dot": 3,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 28
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 61,
   "items": [
    {
     "rule": 16,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 16,
     "dot": 3,
     "lookahead": [
      "'+'",
      "'-'",
      "';'",
      "','",
      "')'",
      "'}'"
     ]
    },
    {
     "rule": 17,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {
    "'*'": {
     "kind": "shift",
     "to": 46
    }
   },
   "default": {
    "kind": "reduce",
    "rule": 16
   },
   "gotos": {},
   "resolved": [
    {
     "rule": 16,
     "token": "'+'",
     "as": "reduce",
     "why": "%left '+'"
    },
    {
     "rule": 16,
     "token": "'-'",
     "as": "reduce",
     "why": "%left '-'"
    },
    {
     "rule": 16,
     "token": "'*'",
     "as": "shift",
     "why": "'+' < '*'"
    }
   ]
  },
  {
   "id": 62,
   "items": [
    {
     "rule": 16,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 3,
     "lookahead": [
      "'+'",
      "'-'",
      "';'",
      "','",
      "')'",
      "'}'"
     ]
    },
    {
     "rule": 18,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {
    "'*'": {
     "kind": "shift",
     "to": 46
    }
   },
   "default": {
    "kind": "reduce",
    "rule": 17
   },
   "gotos": {},
   "resolved": [
    {
     "rule": 17,
     "token": "'+'",
     "as": "reduce",
     "why": "%left '+'"
    },
    {
     "rule": 17,
     "token": "'-'",
     "as": "reduce",
     "why": "%left '-'"
    },
    {
     "rule": 17,
     "token": "'*'",
     "as": "shift",
     "why": "'-' < '*'"
    }
   ]
  },
  {
   "id": 63,
   "items": [
    {
     "rule": 16,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 3,
     "lookahead": [
      "'+'",
      "'-'",
      "'*'",
      "';'",
      "','",
      "')'",
      "'}'"
     ]
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 18
   },
   "gotos": {},
   "resolved": [
    {
     "rule": 18,
     "token": "'+'",
     "as": "reduce",
     "why": "'+' < '*'"
    },
    {
     "rule": 18,
     "token": "'-'",
     "as": "reduce",
     "why": "'-' < '*'"
    },
    {
     "rule": 18,
     "token": "'*'",
     "as": "reduce",
     "why": "%left '*'"
    }
   ]
  },
  {
   "id": 64,
   "items": [
    {
     "rule": 9,
     "dot": 3,
     "lookahead": [
      "' NUMBER '",
      "' . NUMBER '",
      "' '"
     ]
    },
    {
     "rule": 10,
     "dot": 3,
     "lookahead": [
      "' NUMBER '",
      "' . NUMBER '",
      "' '",
      "' expr '"
     ]
    }
   ],
   "actions": {
    "NUMBER": {
     "kind": "shift",
     "to": 75
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 65,
   "items": [
    {
     "rule": 11,
     "dot": 5,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 11
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 66,
   "items": [
    {
     "rule": 13,
     "dot": 5,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 13
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 67,
   "items": [
    {
     "rule": 15,
     "dot": 5,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 15
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 68,
   "items": [
    {
     "rule": 20,
     "dot": 4,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 20
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 69,
   "items": [
    {
     "rule": 21,
     "dot": 4,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 21
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 70,
   "items": [
    {
     "rule": 16,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 19,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 20,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 21,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 22,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 22,
     "dot": 4,
     "lookahead": []
    },
    {
     "rule": 23,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 24,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 25,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 26,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 27,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 28,
     "dot": 0,
     "lookahead": []
    }
   ],
   "actions": {
    "IDENT": {
     "kind": "shift",
     "to": 19
    },
    "NUMBER": {
     "kind": "shift",
     "to": 20
    },
    "KW_TRANSPOSE": {
     "kind": "shift",
     "to": 21
    },
    "KW_IDENTITY": {
     "kind": "shift",
     "to": 22
    },
    "KW_ZEROS": {
     "kind": "shift",
     "to": 23
    },
    "KW_ONES": {
     "kind": "shift",
     "to": 24
    },
    "'-'": {
     "kind": "shift",
     "to": 25
    },
    "'('": {
     "kind": "shift",
     "to": 26
    },
    "'{'": {
     "kind": "shift",
     "to": 27
    }
   },
   "default": null,
   "gotos": {
    "expr": 76,
    "matrix_literal": 29
   },
   "resolved": []
  },
  {
   "id": 71,
   "items": [
    {
     "rule": 16,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 19,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 20,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 21,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 22,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 23,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 23,
     "dot": 4,
     "lookahead": []
    },
    {
     "rule": 24,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 25,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 26,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 27,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 28,
     "dot": 0,
     "lookahead": []
    }
   ],
   "actions": {
    "IDENT": {
     "kind": "shift",
     "to": 19
    },
    "NUMBER": {
     "kind": "shift",
     "to": 20
    },
    "KW_TRANSPOSE": {
     "kind": "shift",
     "to": 21
    },
    "KW_IDENTITY": {
     "kind": "shift",
     "to": 22
    },
    "KW_ZEROS": {
     "kind": "shift",
     "to": 23
    },
    "KW_ONES": {
     "kind": "shift",
     "to": 24
    },
    "'-'": {
     "kind": "shift",
     "to": 25
    },
    "'('": {
     "kind": "shift",
     "to": 26
    },
    "'{'": {
     "kind": "shift",
     "to": 27
    }
   },
   "default": null,
   "gotos": {
    "expr": 77,
    "matrix_literal": 29
   },
   "resolved": []
  },
  {
   "id": 72,
   "items": [
    {
     "rule": 16,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 19,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 20,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 21,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 22,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 23,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 24,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 25,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 26,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 27,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 28,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 33,
     "dot": 2,
     "lookahead": []
    }
   ],
   "actions": {
    "IDENT": {
     "kind": "shift",
     "to": 19
    },
    "NUMBER": {
     "kind": "shift",
     "to": 20
    },
    "KW_TRANSPOSE": {
     "kind": "shift",
     "to": 21
    },
    "KW_IDENTITY": {
     "kind": "shift",
     "to": 22
    },
    "KW_ZEROS": {
     "kind": "shift",
     "to": 23
    },
    "KW_ONES": {
     "kind": "shift",
     "to": 24
    },
    "'-'": {
     "kind": "shift",
     "to": 25
    },
    "'('": {
     "kind": "shift",
     "to": 26
    },
    "'{'": {
     "kind": "shift",
     "to": 27
    }
   },
   "default": null,
   "gotos": {
    "expr": 78,
    "matrix_literal": 29
   },
   "resolved": []
  },
  {
   "id": 73,
   "items": [
    {
     "rule": 31,
     "dot": 3,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 31
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 74,
   "items": [
    {
     "rule": 30,
     "dot": 3,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 30
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 75,
   "items": [
    {
     "rule": 9,
     "dot": 3,
     "lookahead": [
      "' NUMBER '",
      "' NUMBER . '",
      "' '"
     ]
    },
    {
     "rule": 10,
     "dot": 3,
     "lookahead": [
      "' NUMBER '",
      "' NUMBER . '",
      "' '",
      "' expr '"
     ]
    }
   ],
   "actions": {
    "']'": {
     "kind": "shift",
     "to": 79
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 76,
   "items": [
    {
     "rule": 16,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 22,
     "dot": 5,
     "lookahead": []
    }
   ],
   "actions": {
    "'+'": {
     "kind": "shift",
     "to": 44
    },
    "'-'": {
     "kind": "shift",
     "to": 45
    },
    "'*'": {
     "kind": "shift",
     "to": 46
    },
    "')'": {
     "kind": "shift",
     "to": 80
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 77,
   "items": [
    {
     "rule": 16,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 23,
     "dot": 5,
     "lookahead": []
    }
   ],
   "actions": {
    "'+'": {
     "kind": "shift",
     "to": 44
    },
    "'-'": {
     "kind": "shift",
     "to": 45
    },
    "'*'": {
     "kind": "shift",
     "to": 46
    },
    "')'": {
     "kind": "shift",
     "to": 81
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 78,
   "items": [
    {
     "rule": 16,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 33,
     "dot": 3,
     "lookahead": [
      "','",
      "'}'"
     ]
    }
   ],
   "actions": {
    "'+'": {
     "kind": "shift",
     "to": 44
    },
    "'-'": {
     "kind": "shift",
     "to": 45
    },
    "'*'": {
     "kind": "shift",
     "to": 46
    }
   },
   "default": {
    "kind": "reduce",
    "rule": 33
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 79,
   "items": [
    {
     "rule": 9,
     "dot": 3,
     "lookahead": [
      "' NUMBER '",
      "' NUMBER '",
      "' . '"
     ]
    },
    {
     "rule": 10,
     "dot": 3,
     "lookahead": [
      "' NUMBER '",
      "' NUMBER '",
      "' . '",
      "' expr '"
     ]
    }
   ],
   "actions": {
    "';'": {
     "kind": "shift",
     "to": 82
    },
    "'='": {
     "kind": "shift",
     "to": 83
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 80,
   "items": [
    {
     "rule": 22,
     "dot": 6,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 22
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 81,
   "items": [
    {
     "rule": 23,
     "dot": 6,
     "lookahead": []
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 23
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 82,
   "items": [
    {
     "rule": 9,
     "dot": 3,
     "lookahead": [
      "' NUMBER '",
      "' NUMBER '",
      "' '"
     ]
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 9
   },
   "gotos": {},
   "resolved": []
  },
  {
   "id": 83,
   "items": [
    {
     "rule": 10,
     "dot": 3,
     "lookahead": [
      "' NUMBER '",
      "' NUMBER '",
      "' '",
      "' . expr '"
     ]
    },
    {
     "rule": 16,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 19,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 20,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 21,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 22,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 23,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 24,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 25,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 26,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 27,
     "dot": 0,
     "lookahead": []
    },
    {
     "rule": 28,
     "dot": 0,
     "lookahead": []
    }
   ],
   "actions": {
    "IDENT": {
     "kind": "shift",
     "to": 19
    },
    "NUMBER": {
     "kind": "shift",
     "to": 20
    },
    "KW_TRANSPOSE": {
     "kind": "shift",
     "to": 21
    },
    "KW_IDENTITY": {
     "kind": "shift",
     "to": 22
    },
    "KW_ZEROS": {
     "kind": "shift",
     "to": 23
    },
    "KW_ONES": {
     "kind": "shift",
     "to": 24
    },
    "'-'": {
     "kind": "shift",
     "to": 25
    },
    "'('": {
     "kind": "shift",
     "to": 26
    },
    "'{'": {
     "kind": "shift",
     "to": 27
    }
   },
   "default": null,
   "gotos": {
    "expr": 84,
    "matrix_literal": 29
   },
   "resolved": []
  },
  {
   "id": 84,
   "items": [
    {
     "rule": 10,
     "dot": 3,
     "lookahead": [
      "' NUMBER '",
      "' NUMBER '",
      "' '",
      "' expr . '"
     ]
    },
    {
     "rule": 16,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 17,
     "dot": 1,
     "lookahead": []
    },
    {
     "rule": 18,
     "dot": 1,
     "lookahead": []
    }
   ],
   "actions": {
    "'+'": {
     "kind": "shift",
     "to": 44
    },
    "'-'": {
     "kind": "shift",
     "to": 45
    },
    "'*'": {
     "kind": "shift",
     "to": 46
    },
    "';'": {
     "kind": "shift",
     "to": 85
    }
   },
   "default": null,
   "gotos": {},
   "resolved": []
  },
  {
   "id": 85,
   "items": [
    {
     "rule": 10,
     "dot": 3,
     "lookahead": [
      "' NUMBER '",
      "' NUMBER '",
      "' '",
      "' expr '"
     ]
    }
   ],
   "actions": {},
   "default": {
    "kind": "reduce",
    "rule": 10
   },
   "gotos": {},
   "resolved": []
  }
 ],
 "precedence": [
  {
   "level": 1,
   "assoc": "left",
   "tokens": [
    "'+'",
    "'-'"
   ]
  },
  {
   "level": 2,
   "assoc": "left",
   "tokens": [
    "'*'"
   ]
  },
  {
   "level": 3,
   "assoc": "right",
   "tokens": [
    "UMINUS"
   ]
  }
 ],
 "conflicts": {
  "shiftReduce": 0,
  "reduceReduce": 0,
  "resolvedByPrecedence": 12
 },
 "scanner": {
  "definitions": {
   "DIGIT": "[0-9]",
   "LETTER": "[A-Za-z_]",
   "IDENT": "{LETTER}({LETTER}|{DIGIT})*",
   "INTLIT": "{DIGIT}+",
   "REALLIT": "({DIGIT}+\".\"{DIGIT}*|\".\"{DIGIT}+)([eE][+-]?{DIGIT}+)?|{DIGIT}+[eE][+-]?{DIGIT}+"
  },
  "rules": [
   {
    "n": 1,
    "pattern": "[ \\t\\r\\n]+",
    "symbol": null,
    "kind": "skip",
    "category": null
   },
   {
    "n": 2,
    "pattern": "\"//\"[^\\n]*",
    "symbol": null,
    "kind": "skip",
    "category": null
   },
   {
    "n": 3,
    "pattern": "\"/*\"([^*]|\\*+[^*/])*\\*+\"/\"",
    "symbol": null,
    "kind": "skip",
    "category": null
   },
   {
    "n": 4,
    "pattern": "\"/*\"([^*]|\\*+[^*/])*",
    "symbol": null,
    "kind": "error",
    "category": null
   },
   {
    "n": 5,
    "pattern": "\"matrix\"",
    "symbol": "KW_MATRIX",
    "kind": "token",
    "category": "MATRIX"
   },
   {
    "n": 6,
    "pattern": "\"scalar\"",
    "symbol": "KW_SCALAR",
    "kind": "token",
    "category": "SCALAR"
   },
   {
    "n": 7,
    "pattern": "\"print\"",
    "symbol": "KW_PRINT",
    "kind": "token",
    "category": "PRINT"
   },
   {
    "n": 8,
    "pattern": "\"transpose\"",
    "symbol": "KW_TRANSPOSE",
    "kind": "token",
    "category": "TRANSPOSE"
   },
   {
    "n": 9,
    "pattern": "\"identity\"",
    "symbol": "KW_IDENTITY",
    "kind": "token",
    "category": "IDENTITY"
   },
   {
    "n": 10,
    "pattern": "\"zeros\"",
    "symbol": "KW_ZEROS",
    "kind": "token",
    "category": "ZEROS"
   },
   {
    "n": 11,
    "pattern": "\"ones\"",
    "symbol": "KW_ONES",
    "kind": "token",
    "category": "ONES"
   },
   {
    "n": 12,
    "pattern": "{REALLIT}",
    "symbol": "NUMBER",
    "kind": "token",
    "category": "NUMBER"
   },
   {
    "n": 13,
    "pattern": "{INTLIT}",
    "symbol": "NUMBER",
    "kind": "token",
    "category": "NUMBER"
   },
   {
    "n": 14,
    "pattern": "{IDENT}",
    "symbol": "IDENT",
    "kind": "token",
    "category": "IDENTIFIER"
   },
   {
    "n": 15,
    "pattern": "\"+\"",
    "symbol": "'+'",
    "kind": "token",
    "category": "PLUS"
   },
   {
    "n": 16,
    "pattern": "\"-\"",
    "symbol": "'-'",
    "kind": "token",
    "category": "MINUS"
   },
   {
    "n": 17,
    "pattern": "\"*\"",
    "symbol": "'*'",
    "kind": "token",
    "category": "MULTIPLY"
   },
   {
    "n": 18,
    "pattern": "\"=\"",
    "symbol": "'='",
    "kind": "token",
    "category": "ASSIGN"
   },
   {
    "n": 19,
    "pattern": "\"[\"",
    "symbol": "'['",
    "kind": "token",
    "category": "LBRACKET"
   },
   {
    "n": 20,
    "pattern": "\"]\"",
    "symbol": "']'",
    "kind": "token",
    "category": "RBRACKET"
   },
   {
    "n": 21,
    "pattern": "\"(\"",
    "symbol": "'('",
    "kind": "token",
    "category": "LPAREN"
   },
   {
    "n": 22,
    "pattern": "\")\"",
    "symbol": "')'",
    "kind": "token",
    "category": "RPAREN"
   },
   {
    "n": 23,
    "pattern": "\"{\"",
    "symbol": "'{'",
    "kind": "token",
    "category": "LBRACE"
   },
   {
    "n": 24,
    "pattern": "\"}\"",
    "symbol": "'}'",
    "kind": "token",
    "category": "RBRACE"
   },
   {
    "n": 25,
    "pattern": "\",\"",
    "symbol": "','",
    "kind": "token",
    "category": "COMMA"
   },
   {
    "n": 26,
    "pattern": "\";\"",
    "symbol": "';'",
    "kind": "token",
    "category": "SEMICOLON"
   },
   {
    "n": 27,
    "pattern": "{DIGIT}+{LETTER}({LETTER}|{DIGIT})*",
    "symbol": null,
    "kind": "error",
    "category": null
   },
   {
    "n": 28,
    "pattern": ".",
    "symbol": null,
    "kind": "error",
    "category": null
   }
  ]
 }
};
