/* Generated by tools/build-race.py. */
window.MATRIXLANG_RACES = {
 "schema": 1,
 "python": "3.10.11",
 "opener": [
  {
   "title": "Addition is not associative",
   "left": {
    "code": "(0.1 + 0.2) + 0.3",
    "repr": "0.6000000000000001",
    "bits": "3fe3333333333334"
   },
   "right": {
    "code": "0.1 + (0.2 + 0.3)",
    "repr": "0.6",
    "bits": "3fe3333333333333"
   }
  },
  {
   "title": "Summation order changes the total",
   "left": {
    "code": "reduce(add, [0.1] * 10)",
    "repr": "0.9999999999999999",
    "bits": "3fefffffffffffff"
   },
   "right": {
    "code": "math.fsum([0.1] * 10)",
    "repr": "1.0",
    "bits": "3ff0000000000000"
   }
  },
  {
   "title": "Zero has a sign",
   "left": {
    "code": "(-1.0) * 0.0",
    "repr": "-0.0",
    "bits": "8000000000000000"
   },
   "right": {
    "code": "0.0  # x * 0 rewritten to 0",
    "repr": "0.0",
    "bits": "0000000000000000"
   }
  },
  {
   "title": "Reordering can overflow",
   "left": {
    "code": "(1e308 * 10) / 10",
    "repr": "inf",
    "bits": "7ff0000000000000"
   },
   "right": {
    "code": "1e308 * (10 / 10)",
    "repr": "1e+308",
    "bits": "7fe1ccf385ebc8a0"
   }
  }
 ],
 "races": [
  {
   "id": "walks",
   "title": "Graph walks",
   "file": "examples/kernels/walks.ml",
   "description": "Walks of length three from every vertex: A\u00b7A\u00b7A\u00b71 over a 1,024-vertex 0/1 adjacency matrix.",
   "source": "/* Walks of length three from every vertex of a directed graph, written as the\n   textbook formula A^3 1 over the 0/1 adjacency matrix. Every count is an\n   integer below 2^30, so every bracketing is exact. */\nmatrix A[1024,1024] = input(bool);\nmatrix W = A * A * A * ones(1024,1);\nprint(W);\n",
   "runs": {
    "1": {
     "seed": 1,
     "threads": 1,
     "machine": {
      "cpu": "Intel(R) Core(TM) Ultra 9 275HX",
      "gcc": "gcc.EXE (Rev8, Built by MSYS2 project) 15.2.0",
      "logical_cpus": 24,
      "platform": "Windows-11-10.0.26200-SP0",
      "measured": "2026-10-08 12:24"
     },
     "contestants": [
      {
       "id": "ml-strict",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 strict",
       "detail": "proved bit-identical rewrites only",
       "median_ns": 1174200.0,
       "p25_ns": 1164650.0,
       "p75_ns": 1201350.0,
       "samples": 31,
       "note": "Contract: strict. Products whose order of summation is free: 3 of 3 (bit-identical 3, bound-preserving 0, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bit-identical",
          "label": "W"
         }
        ],
        "modeled_after": 6288384,
        "modeled_before": 4294966272
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "W",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "W",
         "index": 0,
         "reference": "41a0c4391a000000",
         "value": "41a0c4391a000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 273.86262987566005
      },
      {
       "id": "ml-bounded",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 bounded",
       "detail": "keeps the source order's error bound",
       "median_ns": 1182100.0,
       "p25_ns": 1167900.0,
       "p75_ns": 1197800.0,
       "samples": 31,
       "note": "Contract: bounded. Products whose order of summation is free: 3 of 3 (bit-identical 3, bound-preserving 0, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bit-identical",
          "label": "W"
         }
        ],
        "modeled_after": 6288384,
        "modeled_before": 4294966272
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "W",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "W",
         "index": 0,
         "reference": "41a0c4391a000000",
         "value": "41a0c4391a000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 272.0323999661619
      },
      {
       "id": "ml-algebraic",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 algebraic",
       "detail": "any rewrite valid over the reals",
       "median_ns": 1175900.0,
       "p25_ns": 1164200.0,
       "p75_ns": 1193850.0,
       "samples": 31,
       "note": "Contract: algebraic. Products whose order of summation is free: 3 of 3 (bit-identical 3, bound-preserving 0, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bit-identical",
          "label": "W"
         }
        ],
        "modeled_after": 6288384,
        "modeled_before": 4294966272
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "W",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "W",
         "index": 0,
         "reference": "41a0c4391a000000",
         "value": "41a0c4391a000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 273.466706352581
      },
      {
       "id": "numpy-matmul",
       "side": "baseline",
       "label": "NumPy  A @ B @ C",
       "detail": "products as written, OpenBLAS",
       "median_ns": 64803599.84561801,
       "p25_ns": 64090749.9473542,
       "p75_ns": 67630099.9475643,
       "samples": 15,
       "note": "NumPy 2.2.6",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "W",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "W",
         "index": 0,
         "reference": "41a0c4391a000000",
         "value": "41a0c4391a000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 4.962216617071843
      },
      {
       "id": "numpy-multidot",
       "side": "baseline",
       "label": "NumPy  multi_dot",
       "detail": "reorders chains for speed, no guarantee",
       "median_ns": 518899.8766243458,
       "p25_ns": 512450.0021338463,
       "p75_ns": 531449.9139785767,
       "samples": 31,
       "note": "NumPy 2.2.6",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "W",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "W",
         "index": 0,
         "reference": "41a0c4391a000000",
         "value": "41a0c4391a000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 619.7139650368392
      },
      {
       "id": "gcc-o3",
       "side": "baseline",
       "label": "GCC -O3",
       "detail": "the program as written, compiled to C",
       "median_ns": 321569500.0,
       "p25_ns": 320737800.0,
       "p75_ns": 328357000.0,
       "samples": 3,
       "note": "Every matrix product keeps the virtual machine's order of summation. ",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "W",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "W",
         "index": 0,
         "reference": "41a0c4391a000000",
         "value": "41a0c4391a000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 1.0
      },
      {
       "id": "gcc-fastmath",
       "side": "baseline",
       "label": "GCC -O3 -ffast-math",
       "detail": "global permission to reassociate",
       "median_ns": 247488000.0,
       "p25_ns": 245708650.0,
       "p75_ns": 280536550.0,
       "samples": 3,
       "note": "Every matrix product keeps the virtual machine's order of summation. ",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "W",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "W",
         "index": 0,
         "reference": "41a0c4391a000000",
         "value": "41a0c4391a000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 1.2993337050685285
      }
     ]
    },
    "8": {
     "seed": 1,
     "threads": 8,
     "machine": {
      "cpu": "Intel(R) Core(TM) Ultra 9 275HX",
      "gcc": "gcc.EXE (Rev8, Built by MSYS2 project) 15.2.0",
      "logical_cpus": 24,
      "platform": "Windows-11-10.0.26200-SP0",
      "measured": "2026-10-08 12:24"
     },
     "contestants": [
      {
       "id": "ml-strict",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 strict",
       "detail": "proved bit-identical rewrites only",
       "median_ns": 329800.0,
       "p25_ns": 280550.0,
       "p75_ns": 380500.0,
       "samples": 31,
       "note": "Contract: strict. Products whose order of summation is free: 3 of 3 (bit-identical 3, bound-preserving 0, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bit-identical",
          "label": "W"
         }
        ],
        "modeled_after": 6288384,
        "modeled_before": 4294966272
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "W",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "W",
         "index": 0,
         "reference": "41a0c4391a000000",
         "value": "41a0c4391a000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 186.0894481503942
      },
      {
       "id": "ml-bounded",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 bounded",
       "detail": "keeps the source order's error bound",
       "median_ns": 265100.0,
       "p25_ns": 251150.0,
       "p75_ns": 294150.0,
       "samples": 31,
       "note": "Contract: bounded. Products whose order of summation is free: 3 of 3 (bit-identical 3, bound-preserving 0, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bit-identical",
          "label": "W"
         }
        ],
        "modeled_after": 6288384,
        "modeled_before": 4294966272
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "W",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "W",
         "index": 0,
         "reference": "41a0c4391a000000",
         "value": "41a0c4391a000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 231.50622406639005
      },
      {
       "id": "ml-algebraic",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 algebraic",
       "detail": "any rewrite valid over the reals",
       "median_ns": 268800.0,
       "p25_ns": 255550.0,
       "p75_ns": 286700.0,
       "samples": 31,
       "note": "Contract: algebraic. Products whose order of summation is free: 3 of 3 (bit-identical 3, bound-preserving 0, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bit-identical",
          "label": "W"
         }
        ],
        "modeled_after": 6288384,
        "modeled_before": 4294966272
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "W",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "W",
         "index": 0,
         "reference": "41a0c4391a000000",
         "value": "41a0c4391a000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 228.31956845238096
      },
      {
       "id": "numpy-matmul",
       "side": "baseline",
       "label": "NumPy  A @ B @ C",
       "detail": "products as written, OpenBLAS",
       "median_ns": 18107600.044459105,
       "p25_ns": 17727449.885569513,
       "p75_ns": 18816299.96933043,
       "samples": 31,
       "note": "NumPy 2.2.6",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "W",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "W",
         "index": 0,
         "reference": "41a0c4391a000000",
         "value": "41a0c4391a000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 3.389311661916225
      },
      {
       "id": "numpy-multidot",
       "side": "baseline",
       "label": "NumPy  multi_dot",
       "detail": "reorders chains for speed, no guarantee",
       "median_ns": 161000.0617802143,
       "p25_ns": 146850.01224279404,
       "p75_ns": 178750.0223144889,
       "samples": 31,
       "note": "NumPy 2.2.6",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "W",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "W",
         "index": 0,
         "reference": "41a0c4391a000000",
         "value": "41a0c4391a000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 381.19426366296085
      },
      {
       "id": "gcc-o3",
       "side": "baseline",
       "label": "GCC -O3",
       "detail": "the program as written, compiled to C",
       "median_ns": 61372300.0,
       "p25_ns": 61020900.0,
       "p75_ns": 62846000.0,
       "samples": 17,
       "note": "Every matrix product keeps the virtual machine's order of summation. ",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "W",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "W",
         "index": 0,
         "reference": "41a0c4391a000000",
         "value": "41a0c4391a000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 1.0
      },
      {
       "id": "gcc-fastmath",
       "side": "baseline",
       "label": "GCC -O3 -ffast-math",
       "detail": "global permission to reassociate",
       "median_ns": 61170400.0,
       "p25_ns": 60652400.0,
       "p75_ns": 62704000.0,
       "samples": 17,
       "note": "Every matrix product keeps the virtual machine's order of summation. ",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "W",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "W",
         "index": 0,
         "reference": "41a0c4391a000000",
         "value": "41a0c4391a000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 1.0033006159842015
      }
     ]
    }
   }
  },
  {
   "id": "layers",
   "title": "Quantized layers",
   "file": "examples/kernels/layers.ml",
   "description": "Two int8 linear layers applied to one uint8 activation vector.",
   "source": "/* Two quantized linear layers with no nonlinearity between them (a factorized\n   projection), applied to one vector of 8-bit activations. */\nmatrix W1[512,1024] = input(int8);\nmatrix W2[16,512] = input(int8);\nmatrix x[1024,1] = input(uint8);\nmatrix y = W2 * W1 * x;\nprint(y);\n",
   "runs": {
    "1": {
     "seed": 1,
     "threads": 1,
     "machine": {
      "cpu": "Intel(R) Core(TM) Ultra 9 275HX",
      "gcc": "gcc.EXE (Rev8, Built by MSYS2 project) 15.2.0",
      "logical_cpus": 24,
      "platform": "Windows-11-10.0.26200-SP0",
      "measured": "2026-10-08 12:24"
     },
     "contestants": [
      {
       "id": "ml-strict",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 strict",
       "detail": "proved bit-identical rewrites only",
       "median_ns": 196800.0,
       "p25_ns": 196200.0,
       "p75_ns": 198250.0,
       "samples": 31,
       "note": "Contract: strict. Products whose order of summation is free: 2 of 2 (bit-identical 2, bound-preserving 0, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bit-identical",
          "label": "y"
         }
        ],
        "modeled_after": 1064432,
        "modeled_before": 16793584
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 16,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "y",
         "index": 0,
         "reference": "41b04bde42000000",
         "value": "41b04bde42000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 5.372459349593496
      },
      {
       "id": "ml-bounded",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 bounded",
       "detail": "keeps the source order's error bound",
       "median_ns": 196800.0,
       "p25_ns": 195750.0,
       "p75_ns": 200800.0,
       "samples": 31,
       "note": "Contract: bounded. Products whose order of summation is free: 2 of 2 (bit-identical 2, bound-preserving 0, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bit-identical",
          "label": "y"
         }
        ],
        "modeled_after": 1064432,
        "modeled_before": 16793584
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 16,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "y",
         "index": 0,
         "reference": "41b04bde42000000",
         "value": "41b04bde42000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 5.372459349593496
      },
      {
       "id": "ml-algebraic",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 algebraic",
       "detail": "any rewrite valid over the reals",
       "median_ns": 211900.0,
       "p25_ns": 208000.0,
       "p75_ns": 218450.0,
       "samples": 31,
       "note": "Contract: algebraic. Products whose order of summation is free: 2 of 2 (bit-identical 2, bound-preserving 0, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bit-identical",
          "label": "y"
         }
        ],
        "modeled_after": 1064432,
        "modeled_before": 16793584
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 16,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "y",
         "index": 0,
         "reference": "41b04bde42000000",
         "value": "41b04bde42000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 4.989617744218971
      },
      {
       "id": "numpy-matmul",
       "side": "baseline",
       "label": "NumPy  A @ B @ C",
       "detail": "products as written, OpenBLAS",
       "median_ns": 399099.89573061466,
       "p25_ns": 396350.04941374063,
       "p75_ns": 404149.9923914671,
       "samples": 31,
       "note": "NumPy 2.2.6",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 16,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "y",
         "index": 0,
         "reference": "41b04bde42000000",
         "value": "41b04bde42000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 2.6492114162657128
      },
      {
       "id": "numpy-multidot",
       "side": "baseline",
       "label": "NumPy  multi_dot",
       "detail": "reorders chains for speed, no guarantee",
       "median_ns": 70600.07192194462,
       "p25_ns": 70200.06887614727,
       "p75_ns": 71499.96235966682,
       "samples": 31,
       "note": "NumPy 2.2.6",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 16,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "y",
         "index": 0,
         "reference": "41b04bde42000000",
         "value": "41b04bde42000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 14.975905423566
      },
      {
       "id": "gcc-o3",
       "side": "baseline",
       "label": "GCC -O3",
       "detail": "the program as written, compiled to C",
       "median_ns": 1057300.0,
       "p25_ns": 945250.0,
       "p75_ns": 1069800.0,
       "samples": 31,
       "note": "Every matrix product keeps the virtual machine's order of summation. ",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 16,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "y",
         "index": 0,
         "reference": "41b04bde42000000",
         "value": "41b04bde42000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 1.0
      },
      {
       "id": "gcc-fastmath",
       "side": "baseline",
       "label": "GCC -O3 -ffast-math",
       "detail": "global permission to reassociate",
       "median_ns": 1136200.0,
       "p25_ns": 1109900.0,
       "p75_ns": 1180400.0,
       "samples": 31,
       "note": "Every matrix product keeps the virtual machine's order of summation. ",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 16,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "y",
         "index": 0,
         "reference": "41b04bde42000000",
         "value": "41b04bde42000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 0.9305580003520507
      }
     ]
    },
    "8": {
     "seed": 1,
     "threads": 8,
     "machine": {
      "cpu": "Intel(R) Core(TM) Ultra 9 275HX",
      "gcc": "gcc.EXE (Rev8, Built by MSYS2 project) 15.2.0",
      "logical_cpus": 24,
      "platform": "Windows-11-10.0.26200-SP0",
      "measured": "2026-10-08 12:24"
     },
     "contestants": [
      {
       "id": "ml-strict",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 strict",
       "detail": "proved bit-identical rewrites only",
       "median_ns": 59800.0,
       "p25_ns": 58650.0,
       "p75_ns": 62050.0,
       "samples": 31,
       "note": "Contract: strict. Products whose order of summation is free: 2 of 2 (bit-identical 2, bound-preserving 0, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bit-identical",
          "label": "y"
         }
        ],
        "modeled_after": 1064432,
        "modeled_before": 16793584
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 16,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "y",
         "index": 0,
         "reference": "41b04bde42000000",
         "value": "41b04bde42000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 3.632107023411371
      },
      {
       "id": "ml-bounded",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 bounded",
       "detail": "keeps the source order's error bound",
       "median_ns": 67700.0,
       "p25_ns": 65550.0,
       "p75_ns": 75950.0,
       "samples": 31,
       "note": "Contract: bounded. Products whose order of summation is free: 2 of 2 (bit-identical 2, bound-preserving 0, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bit-identical",
          "label": "y"
         }
        ],
        "modeled_after": 1064432,
        "modeled_before": 16793584
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 16,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "y",
         "index": 0,
         "reference": "41b04bde42000000",
         "value": "41b04bde42000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 3.208271787296898
      },
      {
       "id": "ml-algebraic",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 algebraic",
       "detail": "any rewrite valid over the reals",
       "median_ns": 58500.0,
       "p25_ns": 57150.0,
       "p75_ns": 62050.0,
       "samples": 31,
       "note": "Contract: algebraic. Products whose order of summation is free: 2 of 2 (bit-identical 2, bound-preserving 0, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bit-identical",
          "label": "y"
         }
        ],
        "modeled_after": 1064432,
        "modeled_before": 16793584
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 16,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "y",
         "index": 0,
         "reference": "41b04bde42000000",
         "value": "41b04bde42000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 3.712820512820513
      },
      {
       "id": "numpy-matmul",
       "side": "baseline",
       "label": "NumPy  A @ B @ C",
       "detail": "products as written, OpenBLAS",
       "median_ns": 130000.05856156349,
       "p25_ns": 124699.9017894268,
       "p75_ns": 257449.92308318615,
       "samples": 31,
       "note": "NumPy 2.2.6",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 16,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "y",
         "index": 0,
         "reference": "41b04bde42000000",
         "value": "41b04bde42000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 1.6707684781321976
      },
      {
       "id": "numpy-multidot",
       "side": "baseline",
       "label": "NumPy  multi_dot",
       "detail": "reorders chains for speed, no guarantee",
       "median_ns": 49399.91049468517,
       "p25_ns": 41550.02534389496,
       "p75_ns": 61350.05969554186,
       "samples": 31,
       "note": "NumPy 2.2.6",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 16,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "y",
         "index": 0,
         "reference": "41b04bde42000000",
         "value": "41b04bde42000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 4.396769099882642
      },
      {
       "id": "gcc-o3",
       "side": "baseline",
       "label": "GCC -O3",
       "detail": "the program as written, compiled to C",
       "median_ns": 217200.0,
       "p25_ns": 208750.0,
       "p75_ns": 240300.0,
       "samples": 31,
       "note": "Every matrix product keeps the virtual machine's order of summation. ",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 16,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "y",
         "index": 0,
         "reference": "41b04bde42000000",
         "value": "41b04bde42000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 1.0
      },
      {
       "id": "gcc-fastmath",
       "side": "baseline",
       "label": "GCC -O3 -ffast-math",
       "detail": "global permission to reassociate",
       "median_ns": 215000.0,
       "p25_ns": 192850.0,
       "p75_ns": 232100.0,
       "samples": 31,
       "note": "Every matrix product keeps the virtual machine's order of summation. ",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 16,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "y",
         "index": 0,
         "reference": "41b04bde42000000",
         "value": "41b04bde42000000",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 1.0102325581395348
      }
     ]
    }
   }
  },
  {
   "id": "diffusion",
   "title": "Diffusion",
   "file": "examples/kernels/diffusion.ml",
   "description": "Three steps of a nonnegative real-valued transition matrix: P\u00b7P\u00b7P\u00b7v.",
   "source": "/* Three steps of a diffusion with a nonnegative transition matrix, written as\n   P^3 v: the real-valued counterpart of walks.ml. */\nmatrix P[1024,1024] = input(real(0,1));\nmatrix v[1024,1] = input(real(0,1));\nmatrix T = P * P * P * v;\nprint(T);\n",
   "runs": {
    "1": {
     "seed": 1,
     "threads": 1,
     "machine": {
      "cpu": "Intel(R) Core(TM) Ultra 9 275HX",
      "gcc": "gcc.EXE (Rev8, Built by MSYS2 project) 15.2.0",
      "logical_cpus": 24,
      "platform": "Windows-11-10.0.26200-SP0",
      "measured": "2026-10-08 12:24"
     },
     "contestants": [
      {
       "id": "ml-strict",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 strict",
       "detail": "proved bit-identical rewrites only",
       "median_ns": 267458400.0,
       "p25_ns": 267424700.0,
       "p75_ns": 271633200.0,
       "samples": 3,
       "note": "Contract: strict. Products whose order of summation is free: 0 of 3 (bit-identical 0, bound-preserving 0, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bit-identical",
          "label": "T"
         }
        ],
        "modeled_after": 4294966272,
        "modeled_before": 4294966272
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "T",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "T",
         "index": 0,
         "reference": "41903b561f2a9e0b",
         "value": "41903b561f2a9e0b",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 0.9602614836550282
      },
      {
       "id": "ml-bounded",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 bounded",
       "detail": "keeps the source order's error bound",
       "median_ns": 1173700.0,
       "p25_ns": 1164750.0,
       "p75_ns": 1189950.0,
       "samples": 31,
       "note": "Contract: bounded. Products whose order of summation is free: 3 of 3 (bit-identical 0, bound-preserving 3, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bound-preserving",
          "label": "T"
         }
        ],
        "modeled_after": 6288384,
        "modeled_before": 4294966272
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "T",
          "entries": 1024,
          "differ": 964,
          "max_rel": 4.5127934751391305e-15
         }
        ],
        "identical": false,
        "worst": {
         "output": "T",
         "index": 921,
         "reference": "41905091af50dffd",
         "value": "41905091af50e000",
         "flipped": 13,
         "rel": 6.532836048365391e-16
        }
       },
       "speedup_vs_source": 218.8208230382551
      },
      {
       "id": "ml-algebraic",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 algebraic",
       "detail": "any rewrite valid over the reals",
       "median_ns": 1181900.0,
       "p25_ns": 1168800.0,
       "p75_ns": 1197550.0,
       "samples": 31,
       "note": "Contract: algebraic. Products whose order of summation is free: 3 of 3 (bit-identical 0, bound-preserving 3, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bound-preserving",
          "label": "T"
         }
        ],
        "modeled_after": 6288384,
        "modeled_before": 4294966272
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "T",
          "entries": 1024,
          "differ": 964,
          "max_rel": 4.5127934751391305e-15
         }
        ],
        "identical": false,
        "worst": {
         "output": "T",
         "index": 921,
         "reference": "41905091af50dffd",
         "value": "41905091af50e000",
         "flipped": 13,
         "rel": 6.532836048365391e-16
        }
       },
       "speedup_vs_source": 217.30264827819613
      },
      {
       "id": "numpy-matmul",
       "side": "baseline",
       "label": "NumPy  A @ B @ C",
       "detail": "products as written, OpenBLAS",
       "median_ns": 73244050.02873391,
       "p25_ns": 72678125.05597249,
       "p75_ns": 73908074.87536222,
       "samples": 14,
       "note": "NumPy 2.2.6",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "T",
          "entries": 1024,
          "differ": 942,
          "max_rel": 2.801434831255779e-15
         }
        ],
        "identical": false,
        "worst": {
         "output": "T",
         "index": 921,
         "reference": "41905091af50dffd",
         "value": "41905091af50e002",
         "flipped": 14,
         "rel": 1.0888060080608986e-15
        }
       },
       "speedup_vs_source": 3.506496430757784
      },
      {
       "id": "numpy-multidot",
       "side": "baseline",
       "label": "NumPy  multi_dot",
       "detail": "reorders chains for speed, no guarantee",
       "median_ns": 530499.9649524689,
       "p25_ns": 520449.9466344714,
       "p75_ns": 556649.9894484878,
       "samples": 31,
       "note": "NumPy 2.2.6",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "T",
          "entries": 1024,
          "differ": 930,
          "max_rel": 2.924810696370957e-15
         }
        ],
        "identical": false,
        "worst": {
         "output": "T",
         "index": 155,
         "reference": "419039751d579fff",
         "value": "419039751d57a002",
         "flipped": 13,
         "rel": 6.569187524198098e-16
        }
       },
       "speedup_vs_source": 484.128212945332
      },
      {
       "id": "gcc-o3",
       "side": "baseline",
       "label": "GCC -O3",
       "detail": "the program as written, compiled to C",
       "median_ns": 256830000.0,
       "p25_ns": 251793050.0,
       "p75_ns": 261203350.0,
       "samples": 3,
       "note": "Every matrix product keeps the virtual machine's order of summation. ",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "T",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "T",
         "index": 0,
         "reference": "41903b561f2a9e0b",
         "value": "41903b561f2a9e0b",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 1.0
      },
      {
       "id": "gcc-fastmath",
       "side": "baseline",
       "label": "GCC -O3 -ffast-math",
       "detail": "global permission to reassociate",
       "median_ns": 267242500.0,
       "p25_ns": 266835350.0,
       "p75_ns": 287556900.0,
       "samples": 3,
       "note": "Every matrix product keeps the virtual machine's order of summation. ",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "T",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "T",
         "index": 0,
         "reference": "41903b561f2a9e0b",
         "value": "41903b561f2a9e0b",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 0.9610372601663283
      }
     ]
    },
    "8": {
     "seed": 1,
     "threads": 8,
     "machine": {
      "cpu": "Intel(R) Core(TM) Ultra 9 275HX",
      "gcc": "gcc.EXE (Rev8, Built by MSYS2 project) 15.2.0",
      "logical_cpus": 24,
      "platform": "Windows-11-10.0.26200-SP0",
      "measured": "2026-10-08 12:24"
     },
     "contestants": [
      {
       "id": "ml-strict",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 strict",
       "detail": "proved bit-identical rewrites only",
       "median_ns": 72391700.0,
       "p25_ns": 66773700.0,
       "p75_ns": 76739300.0,
       "samples": 17,
       "note": "Contract: strict. Products whose order of summation is free: 0 of 3 (bit-identical 0, bound-preserving 0, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bit-identical",
          "label": "T"
         }
        ],
        "modeled_after": 4294966272,
        "modeled_before": 4294966272
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "T",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "T",
         "index": 0,
         "reference": "41903b561f2a9e0b",
         "value": "41903b561f2a9e0b",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 0.8827641842918457
      },
      {
       "id": "ml-bounded",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 bounded",
       "detail": "keeps the source order's error bound",
       "median_ns": 320500.0,
       "p25_ns": 312100.0,
       "p75_ns": 343250.0,
       "samples": 31,
       "note": "Contract: bounded. Products whose order of summation is free: 3 of 3 (bit-identical 0, bound-preserving 3, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bound-preserving",
          "label": "T"
         }
        ],
        "modeled_after": 6288384,
        "modeled_before": 4294966272
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "T",
          "entries": 1024,
          "differ": 964,
          "max_rel": 4.5127934751391305e-15
         }
        ],
        "identical": false,
        "worst": {
         "output": "T",
         "index": 921,
         "reference": "41905091af50dffd",
         "value": "41905091af50e000",
         "flipped": 13,
         "rel": 6.532836048365391e-16
        }
       },
       "speedup_vs_source": 199.39095163806553
      },
      {
       "id": "ml-algebraic",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 algebraic",
       "detail": "any rewrite valid over the reals",
       "median_ns": 319900.0,
       "p25_ns": 311900.0,
       "p75_ns": 332800.0,
       "samples": 31,
       "note": "Contract: algebraic. Products whose order of summation is free: 3 of 3 (bit-identical 0, bound-preserving 3, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bound-preserving",
          "label": "T"
         }
        ],
        "modeled_after": 6288384,
        "modeled_before": 4294966272
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "T",
          "entries": 1024,
          "differ": 964,
          "max_rel": 4.5127934751391305e-15
         }
        ],
        "identical": false,
        "worst": {
         "output": "T",
         "index": 921,
         "reference": "41905091af50dffd",
         "value": "41905091af50e000",
         "flipped": 13,
         "rel": 6.532836048365391e-16
        }
       },
       "speedup_vs_source": 199.7649265395436
      },
      {
       "id": "numpy-matmul",
       "side": "baseline",
       "label": "NumPy  A @ B @ C",
       "detail": "products as written, OpenBLAS",
       "median_ns": 18118900.014087558,
       "p25_ns": 17559050.00027269,
       "p75_ns": 18577249.95352328,
       "samples": 31,
       "note": "NumPy 2.2.6",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "T",
          "entries": 1024,
          "differ": 942,
          "max_rel": 2.801434831255779e-15
         }
        ],
        "identical": false,
        "worst": {
         "output": "T",
         "index": 921,
         "reference": "41905091af50dffd",
         "value": "41905091af50e002",
         "flipped": 14,
         "rel": 1.0888060080608986e-15
        }
       },
       "speedup_vs_source": 3.5269690737469506
      },
      {
       "id": "numpy-multidot",
       "side": "baseline",
       "label": "NumPy  multi_dot",
       "detail": "reorders chains for speed, no guarantee",
       "median_ns": 194099.96457397938,
       "p25_ns": 185299.89756643772,
       "p75_ns": 213399.87870305777,
       "samples": 31,
       "note": "NumPy 2.2.6",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "T",
          "entries": 1024,
          "differ": 930,
          "max_rel": 2.924810696370957e-15
         }
        ],
        "identical": false,
        "worst": {
         "output": "T",
         "index": 155,
         "reference": "419039751d579fff",
         "value": "419039751d57a002",
         "flipped": 13,
         "rel": 6.569187524198098e-16
        }
       },
       "speedup_vs_source": 329.2365361336441
      },
      {
       "id": "gcc-o3",
       "side": "baseline",
       "label": "GCC -O3",
       "detail": "the program as written, compiled to C",
       "median_ns": 63904800.0,
       "p25_ns": 63458800.0,
       "p75_ns": 64592050.0,
       "samples": 15,
       "note": "Every matrix product keeps the virtual machine's order of summation. ",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "T",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "T",
         "index": 0,
         "reference": "41903b561f2a9e0b",
         "value": "41903b561f2a9e0b",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 1.0
      },
      {
       "id": "gcc-fastmath",
       "side": "baseline",
       "label": "GCC -O3 -ffast-math",
       "detail": "global permission to reassociate",
       "median_ns": 70269900.0,
       "p25_ns": 64882900.0,
       "p75_ns": 76302200.0,
       "samples": 17,
       "note": "Every matrix product keeps the virtual machine's order of summation. ",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "T",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "T",
         "index": 0,
         "reference": "41903b561f2a9e0b",
         "value": "41903b561f2a9e0b",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 0.909419253478374
      }
     ]
    }
   }
  },
  {
   "id": "lowrank",
   "title": "Low-rank adapter",
   "file": "examples/kernels/lowrank.ml",
   "description": "A rank-16 real-valued correction B\u00b7A applied to a vector.",
   "source": "/* A rank-16 correction B A applied to a vector, with real-valued factors as\n   in a low-rank adapter. Reordering changes the bits; the bounded contract\n   keeps the source order's error bound. */\nmatrix B[2048,16] = input(real(1));\nmatrix A[16,2048] = input(real(1));\nmatrix x[2048,1] = input(real(1));\nmatrix y = B * A * x;\nprint(y);\n",
   "runs": {
    "1": {
     "seed": 1,
     "threads": 1,
     "machine": {
      "cpu": "Intel(R) Core(TM) Ultra 9 275HX",
      "gcc": "gcc.EXE (Rev8, Built by MSYS2 project) 15.2.0",
      "logical_cpus": 24,
      "platform": "Windows-11-10.0.26200-SP0",
      "measured": "2026-10-08 12:25"
     },
     "contestants": [
      {
       "id": "ml-strict",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 strict",
       "detail": "proved bit-identical rewrites only",
       "median_ns": 11940300.0,
       "p25_ns": 11689600.0,
       "p75_ns": 12309450.0,
       "samples": 31,
       "note": "Contract: strict. Products whose order of summation is free: 0 of 2 (bit-identical 0, bound-preserving 0, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bit-identical",
          "label": "y"
         }
        ],
        "modeled_after": 138409984,
        "modeled_before": 138409984
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 2048,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "y",
         "index": 0,
         "reference": "c03f6a966c552820",
         "value": "c03f6a966c552820",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 1.0012813748398282
      },
      {
       "id": "ml-bounded",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 bounded",
       "detail": "keeps the source order's error bound",
       "median_ns": 22000.0,
       "p25_ns": 21900.0,
       "p75_ns": 22050.0,
       "samples": 31,
       "note": "Contract: bounded. Products whose order of summation is free: 2 of 2 (bit-identical 0, bound-preserving 2, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bound-preserving",
          "label": "y"
         }
        ],
        "modeled_after": 129008,
        "modeled_before": 138409984
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 2048,
          "differ": 2000,
          "max_rel": 1.800266352866794e-12
         }
        ],
        "identical": false,
        "worst": {
         "output": "y",
         "index": 885,
         "reference": "c034810198fabff6",
         "value": "c034810198fac009",
         "flipped": 15,
         "rel": 3.292127793685935e-15
        }
       },
       "speedup_vs_source": 543.4363636363636
      },
      {
       "id": "ml-algebraic",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 algebraic",
       "detail": "any rewrite valid over the reals",
       "median_ns": 24300.0,
       "p25_ns": 22000.0,
       "p75_ns": 24500.0,
       "samples": 31,
       "note": "Contract: algebraic. Products whose order of summation is free: 2 of 2 (bit-identical 0, bound-preserving 2, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bound-preserving",
          "label": "y"
         }
        ],
        "modeled_after": 129008,
        "modeled_before": 138409984
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 2048,
          "differ": 2000,
          "max_rel": 1.800266352866794e-12
         }
        ],
        "identical": false,
        "worst": {
         "output": "y",
         "index": 885,
         "reference": "c034810198fabff6",
         "value": "c034810198fac009",
         "flipped": 15,
         "rel": 3.292127793685935e-15
        }
       },
       "speedup_vs_source": 492.0
      },
      {
       "id": "numpy-matmul",
       "side": "baseline",
       "label": "NumPy  A @ B @ C",
       "detail": "products as written, OpenBLAS",
       "median_ns": 12681300.05337298,
       "p25_ns": 12365599.977783859,
       "p75_ns": 13468999.997712672,
       "samples": 31,
       "note": "NumPy 2.2.6",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 2048,
          "differ": 1981,
          "max_rel": 2.1695668489539084e-12
         }
        ],
        "identical": false,
        "worst": {
         "output": "y",
         "index": 976,
         "reference": "403123d49f698001",
         "value": "403123d49f697ffc",
         "flipped": 15,
         "rel": 1.0363831167450971e-15
        }
       },
       "speedup_vs_source": 0.9427740018516511
      },
      {
       "id": "numpy-multidot",
       "side": "baseline",
       "label": "NumPy  multi_dot",
       "detail": "reorders chains for speed, no guarantee",
       "median_ns": 9200.070053339005,
       "p25_ns": 9099.95287656784,
       "p75_ns": 9350.012987852097,
       "samples": 31,
       "note": "NumPy 2.2.6",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 2048,
          "differ": 1966,
          "max_rel": 2.1350950817411355e-12
         }
        ],
        "identical": false,
        "worst": {
         "output": "y",
         "index": 1774,
         "reference": "bffc059fa47cffb5",
         "value": "bffc059fa47d0108",
         "flipped": 14,
         "rel": 4.2979492783046893e-14
        }
       },
       "speedup_vs_source": 1299.5118440061142
      },
      {
       "id": "gcc-o3",
       "side": "baseline",
       "label": "GCC -O3",
       "detail": "the program as written, compiled to C",
       "median_ns": 11955600.0,
       "p25_ns": 11679450.0,
       "p75_ns": 12296100.0,
       "samples": 31,
       "note": "Every matrix product keeps the virtual machine's order of summation. ",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 2048,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "y",
         "index": 0,
         "reference": "c03f6a966c552820",
         "value": "c03f6a966c552820",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 1.0
      },
      {
       "id": "gcc-fastmath",
       "side": "baseline",
       "label": "GCC -O3 -ffast-math",
       "detail": "global permission to reassociate",
       "median_ns": 12210000.0,
       "p25_ns": 11729200.0,
       "p75_ns": 12689900.0,
       "samples": 31,
       "note": "Every matrix product keeps the virtual machine's order of summation. ",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 2048,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "y",
         "index": 0,
         "reference": "c03f6a966c552820",
         "value": "c03f6a966c552820",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 0.9791646191646192
      }
     ]
    },
    "8": {
     "seed": 1,
     "threads": 8,
     "machine": {
      "cpu": "Intel(R) Core(TM) Ultra 9 275HX",
      "gcc": "gcc.EXE (Rev8, Built by MSYS2 project) 15.2.0",
      "logical_cpus": 24,
      "platform": "Windows-11-10.0.26200-SP0",
      "measured": "2026-10-08 12:25"
     },
     "contestants": [
      {
       "id": "ml-strict",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 strict",
       "detail": "proved bit-identical rewrites only",
       "median_ns": 1812400.0,
       "p25_ns": 1608850.0,
       "p75_ns": 1968950.0,
       "samples": 31,
       "note": "Contract: strict. Products whose order of summation is free: 0 of 2 (bit-identical 0, bound-preserving 0, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bit-identical",
          "label": "y"
         }
        ],
        "modeled_after": 138409984,
        "modeled_before": 138409984
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 2048,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "y",
         "index": 0,
         "reference": "c03f6a966c552820",
         "value": "c03f6a966c552820",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 1.0228426395939085
      },
      {
       "id": "ml-bounded",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 bounded",
       "detail": "keeps the source order's error bound",
       "median_ns": 22400.0,
       "p25_ns": 22300.0,
       "p75_ns": 22400.0,
       "samples": 31,
       "note": "Contract: bounded. Products whose order of summation is free: 2 of 2 (bit-identical 0, bound-preserving 2, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bound-preserving",
          "label": "y"
         }
        ],
        "modeled_after": 129008,
        "modeled_before": 138409984
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 2048,
          "differ": 2000,
          "max_rel": 1.800266352866794e-12
         }
        ],
        "identical": false,
        "worst": {
         "output": "y",
         "index": 885,
         "reference": "c034810198fabff6",
         "value": "c034810198fac009",
         "flipped": 15,
         "rel": 3.292127793685935e-15
        }
       },
       "speedup_vs_source": 82.75892857142857
      },
      {
       "id": "ml-algebraic",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 algebraic",
       "detail": "any rewrite valid over the reals",
       "median_ns": 21600.0,
       "p25_ns": 21500.0,
       "p75_ns": 21600.0,
       "samples": 31,
       "note": "Contract: algebraic. Products whose order of summation is free: 2 of 2 (bit-identical 0, bound-preserving 2, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bound-preserving",
          "label": "y"
         }
        ],
        "modeled_after": 129008,
        "modeled_before": 138409984
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 2048,
          "differ": 2000,
          "max_rel": 1.800266352866794e-12
         }
        ],
        "identical": false,
        "worst": {
         "output": "y",
         "index": 885,
         "reference": "c034810198fabff6",
         "value": "c034810198fac009",
         "flipped": 15,
         "rel": 3.292127793685935e-15
        }
       },
       "speedup_vs_source": 85.82407407407408
      },
      {
       "id": "numpy-matmul",
       "side": "baseline",
       "label": "NumPy  A @ B @ C",
       "detail": "products as written, OpenBLAS",
       "median_ns": 7846900.029107928,
       "p25_ns": 7564549.916423857,
       "p75_ns": 8139499.928802252,
       "samples": 31,
       "note": "NumPy 2.2.6",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 2048,
          "differ": 1981,
          "max_rel": 2.1695668489539084e-12
         }
        ],
        "identical": false,
        "worst": {
         "output": "y",
         "index": 976,
         "reference": "403123d49f698001",
         "value": "403123d49f697ffc",
         "flipped": 15,
         "rel": 1.0363831167450971e-15
        }
       },
       "speedup_vs_source": 0.23624616002795545
      },
      {
       "id": "numpy-multidot",
       "side": "baseline",
       "label": "NumPy  multi_dot",
       "detail": "reorders chains for speed, no guarantee",
       "median_ns": 9899.958968162537,
       "p25_ns": 9699.957445263863,
       "p75_ns": 10050.018317997456,
       "samples": 31,
       "note": "NumPy 2.2.6",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 2048,
          "differ": 1966,
          "max_rel": 2.1350950817411355e-12
         }
        ],
        "identical": false,
        "worst": {
         "output": "y",
         "index": 1774,
         "reference": "bffc059fa47cffb5",
         "value": "bffc059fa47d0108",
         "flipped": 14,
         "rel": 4.2979492783046893e-14
        }
       },
       "speedup_vs_source": 187.25330134818438
      },
      {
       "id": "gcc-o3",
       "side": "baseline",
       "label": "GCC -O3",
       "detail": "the program as written, compiled to C",
       "median_ns": 1853800.0,
       "p25_ns": 1788850.0,
       "p75_ns": 2065850.0,
       "samples": 31,
       "note": "Every matrix product keeps the virtual machine's order of summation. ",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 2048,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "y",
         "index": 0,
         "reference": "c03f6a966c552820",
         "value": "c03f6a966c552820",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 1.0
      },
      {
       "id": "gcc-fastmath",
       "side": "baseline",
       "label": "GCC -O3 -ffast-math",
       "detail": "global permission to reassociate",
       "median_ns": 1775400.0,
       "p25_ns": 1689450.0,
       "p75_ns": 1919250.0,
       "samples": 31,
       "note": "Every matrix product keeps the virtual machine's order of summation. ",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "y",
          "entries": 2048,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "y",
         "index": 0,
         "reference": "c03f6a966c552820",
         "value": "c03f6a966c552820",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 1.0441590627464234
      }
     ]
    }
   }
  },
  {
   "id": "overflow",
   "title": "Overflow trap",
   "file": "examples/race/overflow_trap.ml",
   "description": "The cheaper bracketing overflows: B\u00b7C multiplies values near 1e200.",
   "source": "/* The cheaper bracketing overflows. Written left to right, A * B holds values\n   near 1 and the result is finite. Reordered, B * C multiplies two values\n   near 1e200 and overflows to infinity before A can scale it back. The facts\n   see the overflow coming, so strict and bounded keep the source order;\n   only algebraic reorders, and labels the output relaxed. */\nmatrix A[1024,1] = input(real(1e-200, 2e-200));\nmatrix B[1,1024] = input(real(1e199, 1e200));\nmatrix C[1024,1] = input(real(1e199, 1e200));\nmatrix R = A * B * C;\nprint(R);\n",
   "runs": {
    "1": {
     "seed": 1,
     "threads": 1,
     "machine": {
      "cpu": "Intel(R) Core(TM) Ultra 9 275HX",
      "gcc": "gcc.EXE (Rev8, Built by MSYS2 project) 15.2.0",
      "logical_cpus": 24,
      "platform": "Windows-11-10.0.26200-SP0",
      "measured": "2026-10-08 12:25"
     },
     "contestants": [
      {
       "id": "ml-strict",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 strict",
       "detail": "proved bit-identical rewrites only",
       "median_ns": 659200.0,
       "p25_ns": 652900.0,
       "p75_ns": 671000.0,
       "samples": 31,
       "note": "Contract: strict. Products whose order of summation is free: 0 of 2 (bit-identical 0, bound-preserving 0, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bit-identical",
          "label": "R"
         }
        ],
        "modeled_after": 3144704,
        "modeled_before": 3144704
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "R",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "R",
         "index": 0,
         "reference": "6a027243892ff5ac",
         "value": "6a027243892ff5ac",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 1.015625
      },
      {
       "id": "ml-bounded",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 bounded",
       "detail": "keeps the source order's error bound",
       "median_ns": 622300.0,
       "p25_ns": 612000.0,
       "p75_ns": 628800.0,
       "samples": 31,
       "note": "Contract: bounded. Products whose order of summation is free: 2 of 2 (bit-identical 0, bound-preserving 2, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bit-identical",
          "label": "R"
         }
        ],
        "modeled_after": 3144704,
        "modeled_before": 3144704
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "R",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "R",
         "index": 0,
         "reference": "6a027243892ff5ac",
         "value": "6a027243892ff5ac",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 1.0758476618994055
      },
      {
       "id": "ml-algebraic",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 algebraic",
       "detail": "any rewrite valid over the reals",
       "median_ns": 300.0,
       "p25_ns": 200.0,
       "p75_ns": 300.0,
       "samples": 31,
       "note": "Contract: algebraic. Products whose order of summation is free: 2 of 2 (bit-identical 0, bound-preserving 0, relaxed 2).",
       "guarantees": {
        "levels": [
         {
          "level": "relaxed",
          "label": "R"
         }
        ],
        "modeled_after": 3071,
        "modeled_before": 3144704
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "R",
          "entries": 1024,
          "differ": 1024,
          "max_rel": Infinity
         }
        ],
        "identical": false,
        "worst": {
         "output": "R",
         "index": 364,
         "reference": "6a02d5ef9d5debf5",
         "value": "7ff0000000000000",
         "flipped": 42,
         "rel": null
        }
       },
       "speedup_vs_source": 2231.6666666666665
      },
      {
       "id": "numpy-matmul",
       "side": "baseline",
       "label": "NumPy  A @ B @ C",
       "detail": "products as written, OpenBLAS",
       "median_ns": 3183800.0286370516,
       "p25_ns": 3135100.00705719,
       "p75_ns": 3246200.0381201506,
       "samples": 31,
       "note": "NumPy 2.2.6",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "R",
          "entries": 1024,
          "differ": 942,
          "max_rel": 3.4026996745850228e-15
         }
        ],
        "identical": false,
        "worst": {
         "output": "R",
         "index": 823,
         "reference": "69fe10b6b4ed8bfc",
         "value": "69fe10b6b4ed8c03",
         "flipped": 11,
         "rel": 8.271663936084235e-16
        }
       },
       "speedup_vs_source": 0.21028330736167664
      },
      {
       "id": "numpy-multidot",
       "side": "baseline",
       "label": "NumPy  multi_dot",
       "detail": "reorders chains for speed, no guarantee",
       "median_ns": 2299.901098012924,
       "p25_ns": 2200.016751885414,
       "p75_ns": 2450.07686316967,
       "samples": 31,
       "note": "NumPy 2.2.6",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "R",
          "entries": 1024,
          "differ": 1024,
          "max_rel": Infinity
         }
        ],
        "identical": false,
        "worst": {
         "output": "R",
         "index": 364,
         "reference": "6a02d5ef9d5debf5",
         "value": "7ff0000000000000",
         "flipped": 42,
         "rel": null
        }
       },
       "speedup_vs_source": 291.0994740506175
      },
      {
       "id": "gcc-o3",
       "side": "baseline",
       "label": "GCC -O3",
       "detail": "the program as written, compiled to C",
       "median_ns": 669500.0,
       "p25_ns": 664700.0,
       "p75_ns": 673950.0,
       "samples": 31,
       "note": "Every matrix product keeps the virtual machine's order of summation. ",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "R",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "R",
         "index": 0,
         "reference": "6a027243892ff5ac",
         "value": "6a027243892ff5ac",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 1.0
      },
      {
       "id": "gcc-fastmath",
       "side": "baseline",
       "label": "GCC -O3 -ffast-math",
       "detail": "global permission to reassociate",
       "median_ns": 644400.0,
       "p25_ns": 638800.0,
       "p75_ns": 650300.0,
       "samples": 31,
       "note": "Every matrix product keeps the virtual machine's order of summation. ",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "R",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "R",
         "index": 0,
         "reference": "6a027243892ff5ac",
         "value": "6a027243892ff5ac",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 1.0389509621353197
      }
     ]
    },
    "8": {
     "seed": 1,
     "threads": 8,
     "machine": {
      "cpu": "Intel(R) Core(TM) Ultra 9 275HX",
      "gcc": "gcc.EXE (Rev8, Built by MSYS2 project) 15.2.0",
      "logical_cpus": 24,
      "platform": "Windows-11-10.0.26200-SP0",
      "measured": "2026-10-08 12:25"
     },
     "contestants": [
      {
       "id": "ml-strict",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 strict",
       "detail": "proved bit-identical rewrites only",
       "median_ns": 172900.0,
       "p25_ns": 164750.0,
       "p75_ns": 195800.0,
       "samples": 31,
       "note": "Contract: strict. Products whose order of summation is free: 0 of 2 (bit-identical 0, bound-preserving 0, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bit-identical",
          "label": "R"
         }
        ],
        "modeled_after": 3144704,
        "modeled_before": 3144704
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "R",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "R",
         "index": 0,
         "reference": "6a027243892ff5ac",
         "value": "6a027243892ff5ac",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 0.9323308270676691
      },
      {
       "id": "ml-bounded",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 bounded",
       "detail": "keeps the source order's error bound",
       "median_ns": 192200.0,
       "p25_ns": 183300.0,
       "p75_ns": 207100.0,
       "samples": 31,
       "note": "Contract: bounded. Products whose order of summation is free: 2 of 2 (bit-identical 0, bound-preserving 2, relaxed 0).",
       "guarantees": {
        "levels": [
         {
          "level": "bit-identical",
          "label": "R"
         }
        ],
        "modeled_after": 3144704,
        "modeled_before": 3144704
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "R",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "R",
         "index": 0,
         "reference": "6a027243892ff5ac",
         "value": "6a027243892ff5ac",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 0.8387096774193549
      },
      {
       "id": "ml-algebraic",
       "side": "matrixlang",
       "label": "MatrixLang \u00b7 algebraic",
       "detail": "any rewrite valid over the reals",
       "median_ns": 300.0,
       "p25_ns": 200.0,
       "p75_ns": 300.0,
       "samples": 31,
       "note": "Contract: algebraic. Products whose order of summation is free: 2 of 2 (bit-identical 0, bound-preserving 0, relaxed 2).",
       "guarantees": {
        "levels": [
         {
          "level": "relaxed",
          "label": "R"
         }
        ],
        "modeled_after": 3071,
        "modeled_before": 3144704
       },
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "R",
          "entries": 1024,
          "differ": 1024,
          "max_rel": Infinity
         }
        ],
        "identical": false,
        "worst": {
         "output": "R",
         "index": 364,
         "reference": "6a02d5ef9d5debf5",
         "value": "7ff0000000000000",
         "flipped": 42,
         "rel": null
        }
       },
       "speedup_vs_source": 537.3333333333334
      },
      {
       "id": "numpy-matmul",
       "side": "baseline",
       "label": "NumPy  A @ B @ C",
       "detail": "products as written, OpenBLAS",
       "median_ns": 3153099.911287427,
       "p25_ns": 3072600.1132279634,
       "p75_ns": 3330049.919895828,
       "samples": 31,
       "note": "NumPy 2.2.6",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "R",
          "entries": 1024,
          "differ": 942,
          "max_rel": 3.4026996745850228e-15
         }
        ],
        "identical": false,
        "worst": {
         "output": "R",
         "index": 823,
         "reference": "69fe10b6b4ed8bfc",
         "value": "69fe10b6b4ed8c03",
         "flipped": 11,
         "rel": 8.271663936084235e-16
        }
       },
       "speedup_vs_source": 0.05112429181927864
      },
      {
       "id": "numpy-multidot",
       "side": "baseline",
       "label": "NumPy  multi_dot",
       "detail": "reorders chains for speed, no guarantee",
       "median_ns": 2300.133928656578,
       "p25_ns": 2249.958924949169,
       "p75_ns": 2449.960447847843,
       "samples": 31,
       "note": "NumPy 2.2.6",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "R",
          "entries": 1024,
          "differ": 1024,
          "max_rel": Infinity
         }
        ],
        "identical": false,
        "worst": {
         "output": "R",
         "index": 364,
         "reference": "6a02d5ef9d5debf5",
         "value": "7ff0000000000000",
         "flipped": 42,
         "rel": null
        }
       },
       "speedup_vs_source": 70.08287560635692
      },
      {
       "id": "gcc-o3",
       "side": "baseline",
       "label": "GCC -O3",
       "detail": "the program as written, compiled to C",
       "median_ns": 161200.0,
       "p25_ns": 154850.0,
       "p75_ns": 177000.0,
       "samples": 31,
       "note": "Every matrix product keeps the virtual machine's order of summation. ",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "R",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "R",
         "index": 0,
         "reference": "6a027243892ff5ac",
         "value": "6a027243892ff5ac",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 1.0
      },
      {
       "id": "gcc-fastmath",
       "side": "baseline",
       "label": "GCC -O3 -ffast-math",
       "detail": "global permission to reassociate",
       "median_ns": 166500.0,
       "p25_ns": 162500.0,
       "p75_ns": 184500.0,
       "samples": 31,
       "note": "Every matrix product keeps the virtual machine's order of summation. ",
       "bits": {
        "comparable": true,
        "outputs": [
         {
          "label": "R",
          "entries": 1024,
          "differ": 0,
          "max_rel": 0.0
         }
        ],
        "identical": true,
        "worst": {
         "output": "R",
         "index": 0,
         "reference": "6a027243892ff5ac",
         "value": "6a027243892ff5ac",
         "flipped": 0,
         "rel": 0.0
        }
       },
       "speedup_vs_source": 0.9681681681681682
      }
     ]
    }
   }
  }
 ]
};
