"""Generate the workspace's recorded examples using the local compiler adapter."""

import hashlib
import json
from pathlib import Path
import re

from demo_service import ROOT, binary_path, compile_source

EXAMPLES = [
    ("multiply", "Matrix product", "Infer a result shape and execute a matrix product.", "examples/valid/multiply.ml", "check"),
    ("chain", "Chain ordering", "Compare source order with a cheaper algebraic association.", "examples/optimize/chain_order.ml", "optimize"),
    ("mismatch", "Shape mismatch", "Inspect a dimension error before code generation.", "examples/errors/mul_mismatch.ml", "check"),
    ("reuse", "Expression reuse", "Inspect common subexpressions and intermediate code.", "examples/optimize/cse.ml", "optimize"),
    ("numerics", "Signed zero", "Observe a numerical change permitted by algebraic mode.", "examples/demo/signed_zero.ml", "execute"),
]


def main():
    examples = []
    for key, title, description, file, stage in EXAMPLES:
        source = (ROOT / file).read_text(encoding="utf-8")
        source = re.sub(r"^\s*/\*.*?\*/\s*", "", source, flags=re.S).strip()
        captures = {mode: compile_source(source, mode) for mode in ("strict", "algebraic")}
        examples.append({"id": key, "title": title, "description": description,
                         "file": file, "stage": stage, "source": source, "captures": captures})
        print(f"Captured {title}: strict and algebraic")
    data = {"schema": 1, "compilerHash": hashlib.sha256(binary_path().read_bytes()).hexdigest(),
            "examples": examples}
    output = ROOT / "demo/workspace-data.js"
    output.write_text("/* Generated by tools/build-workspace.py. */\nwindow.MATRIXLANG_WORKSPACE = " +
                      json.dumps(data, ensure_ascii=False, indent=2) + ";\n", encoding="utf-8", newline="\n")
    print(f"Wrote {output.relative_to(ROOT).as_posix()}")


if __name__ == "__main__":
    main()
