"""Record the workspace's races and its floating-point opener.

Runs tools/race.py on the race programs at one thread and at eight, and
evaluates the opener's Python expressions in this interpreter, then writes
demo/race-data.js. Every number the Race and Results views show without the
local service comes from this file; with the service running, the Race view
measures again on the spot.

    python tools/build-race.py [--budget SECONDS]
"""

import argparse
import functools
import json
import math
import operator
from pathlib import Path
import platform
import struct
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
import race  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
RACES = [
    ("walks", "Graph walks", "examples/kernels/walks.ml",
     "Walks of length three from every vertex: A·A·A·1 over a 1,024-vertex 0/1 adjacency matrix."),
    ("layers", "Quantized layers", "examples/kernels/layers.ml",
     "Two int8 linear layers applied to one uint8 activation vector."),
    ("diffusion", "Diffusion", "examples/kernels/diffusion.ml",
     "Three steps of a nonnegative real-valued transition matrix: P·P·P·v."),
    ("lowrank", "Low-rank adapter", "examples/kernels/lowrank.ml",
     "A rank-16 real-valued correction B·A applied to a vector."),
    ("overflow", "Overflow trap", "examples/race/overflow_trap.ml",
     "The cheaper bracketing overflows: B·C multiplies values near 1e200."),
]
THREADS = (1, 8)


def bits(x):
    return f"{struct.unpack('<Q', struct.pack('<d', x))[0]:016x}"


def opener():
    """Python's own answers, evaluated here, with their binary64 bits."""
    def case(code, value):
        return {"code": code, "repr": repr(value), "bits": bits(value)}
    return [
        {"title": "Addition is not associative",
         "left": case("(0.1 + 0.2) + 0.3", (0.1 + 0.2) + 0.3),
         "right": case("0.1 + (0.2 + 0.3)", 0.1 + (0.2 + 0.3))},
        {"title": "Summation order changes the total",
         "left": case("reduce(add, [0.1] * 10)", functools.reduce(operator.add, [0.1] * 10)),
         "right": case("math.fsum([0.1] * 10)", math.fsum([0.1] * 10))},
        {"title": "Zero has a sign",
         "left": case("0.0 * 1.0", 0.0 * 1.0),
         "right": case("0.0 * -1.0", 0.0 * -1.0)},
        {"title": "Reordering can overflow",
         "left": case("(1e308 * 10) / 10", (1e308 * 10) / 10),
         "right": case("1e308 * (10 / 10)", 1e308 * (10 / 10))},
    ]


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--budget", type=float, default=1.0)
    parser.add_argument("--opener-only", action="store_true", help="refresh the opener, keep the recorded races")
    args = parser.parse_args()
    out = ROOT / "demo" / "race-data.js"
    if args.opener_only:
        data = json.loads(out.read_text(encoding="utf-8").split("window.MATRIXLANG_RACES = ", 1)[1].rstrip(";\n"))
        data["opener"], data["python"] = opener(), platform.python_version()
        write(out, data)
        print(f"Refreshed the opener in {out.relative_to(ROOT).as_posix()}")
        return
    races = []
    for key, title, path, description in RACES:
        source = (ROOT / path).read_text(encoding="utf-8")
        runs = {}
        for threads in THREADS:
            print(f"race {key}, {threads} thread(s) ...", flush=True)
            runs[str(threads)] = race.race(source, seed=1, budget=args.budget, threads=threads)
        races.append({"id": key, "title": title, "file": path, "description": description,
                      "source": source, "runs": runs})
    data = {"schema": 1, "python": platform.python_version(), "opener": opener(), "races": races}
    write(out, data)
    print(f"Wrote {out.relative_to(ROOT).as_posix()}")


def write(out, data):
    out.write_text("/* Generated by tools/build-race.py. */\nwindow.MATRIXLANG_RACES = "
                   + json.dumps(data, indent=1) + ";\n", encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
