"""Generate the workspace's recorded examples using the local compiler adapter."""

import hashlib
import json
from pathlib import Path
import re

from demo_service import CONTRACTS, DEFAULT_SEED, ROOT, binary_path, compile_source

EXAMPLES = [
    ("multiply", "Matrix product", "Infer a result shape and execute a matrix product.", "examples/valid/multiply.ml", "check"),
    ("exact", "Exact integer chain", "Reorder an int8 chain under the strict contract, proved bit-identical from its input domains.", "examples/demo/exact_chain.ml", "guarantees"),
    ("real", "Real-valued chain", "Keep the source order under strict; reorder under bounded with a certified error bound.", "examples/demo/real_chain.ml", "guarantees"),
    ("outputs", "Per-output guarantees", "Certify two outputs of one program at different guarantee levels.", "examples/demo/two_outputs.ml", "guarantees"),
    ("unbounded", "Unbounded reals", "Reorder only under algebraic, where no error bound is kept, and certify the output as relaxed.", "examples/demo/unbounded_chain.ml", "guarantees"),
    ("numerics", "Signed zero", "Remove a zero product only where the contract permits -0 to become +0.", "examples/demo/signed_zero.ml", "guarantees"),
    ("inherited", "Inherited guarantee", "Keep a weaker guarantee when a later proof relies on the facts it produced.", "examples/contracts/inherited_guarantee.ml", "guarantees"),
    ("mismatch", "Shape mismatch", "Inspect a dimension error before code generation.", "examples/errors/mul_mismatch.ml", "check"),
    ("reuse", "Expression reuse", "Inspect common subexpressions and intermediate code.", "examples/optimize/cse.ml", "optimize"),
]


def main():
    examples = []
    for key, title, description, file, stage in EXAMPLES:
        source = (ROOT / file).read_text(encoding="utf-8")
        source = re.sub(r"^\s*/\*.*?\*/\s*", "", source, flags=re.S).strip()
        captures = {mode: compile_source(source, mode, DEFAULT_SEED) for mode in CONTRACTS}
        examples.append({"id": key, "title": title, "description": description,
                         "file": file, "stage": stage, "source": source, "captures": captures})
        print(f"Captured {title}: {', '.join(CONTRACTS)}")
    data = {"schema": 2, "compilerHash": hashlib.sha256(binary_path().read_bytes()).hexdigest(),
            "seed": DEFAULT_SEED, "contracts": list(CONTRACTS), "examples": examples}
    output = ROOT / "demo/workspace-data.js"
    output.write_text("/* Generated by tools/build-workspace.py. */\nwindow.MATRIXLANG_WORKSPACE = " +
                      json.dumps(data, ensure_ascii=False, indent=2) + ";\n", encoding="utf-8", newline="\n")
    print(f"Wrote {output.relative_to(ROOT).as_posix()}")


if __name__ == "__main__":
    main()
